function varargout=sym_sd_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=6;
   return
  case 'tp_del'
   varargout{1}=1;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_sd_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2,out3,out4,out5] = sym_sd_demo_rhs_1_0(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_RHS_1_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5] = SYM_SD_DEMO_RHS_1_0(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:43

t2 = p1+x2_1;
t3 = 1.0./t2;
out1 = t3.*(p3.*x1_2.*x2_3-p2.*x1_1.*x1_4.*x3_4+1.0);
if nargout > 1
    out2 = p5.*tanh(x2_6)+p4.*t3.*x1_1-1.0;
end
if nargout > 2
    out3 = p6.*(x2_1-x3_1)-p7.*exp(-p8.*x4_1).*(x1_7-x2_5);
end
if nargout > 3
    out4 = x1_5.*exp(-p1.*x4_1)-1.0./1.0e1;
end
if nargout > 4
    out5 = -p9+x1_3.*3.0-x5_1.*3.0;
end


function [out1,out2,out3,out4,out5] = sym_sd_demo_rhs_1_1(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_RHS_1_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5] = SYM_SD_DEMO_RHS_1_1(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:43

t2 = p1+x2_1;
t3 = 1.0./t2;
t4 = tanh(x2_6);
t5 = 1.0./t2.^2;
t6 = p1_d+x2_1_d;
out1 = -t3.*(-p3.*x1_2.*x2_3_d-p3.*x2_3.*x1_2_d-p3_d.*x1_2.*x2_3+p2.*x1_1.*x1_4.*x3_4_d+p2.*x1_1.*x3_4.*x1_4_d+p2.*x1_4.*x3_4.*x1_1_d+p2_d.*x1_1.*x1_4.*x3_4)-t5.*t6.*(p3.*x1_2.*x2_3-p2.*x1_1.*x1_4.*x3_4+1.0);
if nargout > 1
    out2 = p5_d.*t4-p5.*x2_6_d.*(t4.^2-1.0)+p4.*t3.*x1_1_d+p4_d.*t3.*x1_1-p4.*t5.*t6.*x1_1;
end
if nargout > 2
    t8 = p8.*x4_1;
    t7 = exp(-t8);
    t9 = x1_7-x2_5;
    out3 = p6.*(x2_1_d-x3_1_d)+p6_d.*(x2_1-x3_1)-p7_d.*t7.*t9-p7.*t7.*(x1_7_d-x2_5_d)+p7.*t7.*t9.*(p8.*x4_1_d+p8_d.*x4_1);
end
if nargout > 3
    t10 = exp(-p1.*x4_1);
    out4 = t10.*x1_5_d-t10.*x1_5.*(p1.*x4_1_d+p1_d.*x4_1);
end
if nargout > 4
    out5 = -p9_d+x1_3_d.*3.0-x5_1_d.*3.0;
end


function [out1,out2,out3,out4,out5] = sym_sd_demo_rhs_1_2(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_RHS_1_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5] = SYM_SD_DEMO_RHS_1_2(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:43

t2 = p1+x2_1;
t3 = p1_d+x2_1_d;
t4 = 1.0./t2;
t5 = tanh(x2_6);
t6 = 1.0./t2.^2;
t7 = t5.^2;
t8 = t7-1.0;
t9 = 1.0./t2.^3;
t10 = t3.^2;
out1 = -t4.*(p3.*x1_2_d.*x2_3_d.*-2.0-p3_d.*x1_2.*x2_3_d.*2.0-p3_d.*x2_3.*x1_2_d.*2.0+p2.*x1_1.*x1_4_d.*x3_4_d.*2.0+p2.*x1_4.*x1_1_d.*x3_4_d.*2.0+p2.*x3_4.*x1_1_d.*x1_4_d.*2.0+p2_d.*x1_1.*x1_4.*x3_4_d.*2.0+p2_d.*x1_1.*x3_4.*x1_4_d.*2.0+p2_d.*x1_4.*x3_4.*x1_1_d.*2.0)+t9.*t10.*(p3.*x1_2.*x2_3-p2.*x1_1.*x1_4.*x3_4+1.0).*2.0+t3.*t6.*(-p3.*x1_2.*x2_3_d-p3.*x2_3.*x1_2_d-p3_d.*x1_2.*x2_3+p2.*x1_1.*x1_4.*x3_4_d+p2.*x1_1.*x3_4.*x1_4_d+p2.*x1_4.*x3_4.*x1_1_d+p2_d.*x1_1.*x1_4.*x3_4).*2.0;
if nargout > 1
    out2 = p4_d.*t4.*x1_1_d.*2.0-p5_d.*t8.*x2_6_d.*2.0+p4.*t9.*t10.*x1_1.*2.0-p4.*t3.*t6.*x1_1_d.*2.0-p4_d.*t3.*t6.*x1_1.*2.0+p5.*t5.*t8.*x2_6_d.^2.*2.0;
end
if nargout > 2
    t13 = p8.*x4_1;
    t11 = exp(-t13);
    t12 = x1_7_d-x2_5_d;
    t14 = p8.*x4_1_d;
    t15 = p8_d.*x4_1;
    t16 = t14+t15;
    t17 = x1_7-x2_5;
    out3 = p6_d.*(x2_1_d-x3_1_d).*2.0-p7_d.*t11.*t12.*2.0+p7.*t11.*t12.*t16.*2.0+p7_d.*t11.*t16.*t17.*2.0-p7.*t11.*t16.^2.*t17+p7.*p8_d.*t11.*t17.*x4_1_d.*2.0;
end
if nargout > 3
    t22 = p1.*x4_1;
    t18 = exp(-t22);
    t19 = p1.*x4_1_d;
    t20 = p1_d.*x4_1;
    t21 = t19+t20;
    out4 = t18.*t21.^2.*x1_5-t18.*t21.*x1_5_d.*2.0-p1_d.*t18.*x1_5.*x4_1_d.*2.0;
end
if nargout > 4
    out5 = 0.0;
end


function [out1,out2,out3,out4,out5] = sym_sd_demo_rhs_1_3(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_RHS_1_3
%    [OUT1,OUT2,OUT3,OUT4,OUT5] = SYM_SD_DEMO_RHS_1_3(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:44

t2 = p1+x2_1;
t3 = p1_d+x2_1_d;
t4 = t3.^2;
t5 = x2_6_d.^2;
t6 = tanh(x2_6);
t9 = t6.^2;
t7 = t9-1.0;
t8 = 1.0./t2.^2;
t10 = 1.0./t2.^4;
t11 = 1.0./t2.^3;
out1 = -(p3_d.*x1_2_d.*x2_3_d.*-6.0+p2.*x1_1_d.*x1_4_d.*x3_4_d.*6.0+p2_d.*x1_1.*x1_4_d.*x3_4_d.*6.0+p2_d.*x1_4.*x1_1_d.*x3_4_d.*6.0+p2_d.*x3_4.*x1_1_d.*x1_4_d.*6.0)./t2+t3.*t8.*(p3.*x1_2_d.*x2_3_d.*-2.0-p3_d.*x1_2.*x2_3_d.*2.0-p3_d.*x2_3.*x1_2_d.*2.0+p2.*x1_1.*x1_4_d.*x3_4_d.*2.0+p2.*x1_4.*x1_1_d.*x3_4_d.*2.0+p2.*x3_4.*x1_1_d.*x1_4_d.*2.0+p2_d.*x1_1.*x1_4.*x3_4_d.*2.0+p2_d.*x1_1.*x3_4.*x1_4_d.*2.0+p2_d.*x1_4.*x3_4.*x1_1_d.*2.0).*3.0-t4.*t11.*(-p3.*x1_2.*x2_3_d-p3.*x2_3.*x1_2_d-p3_d.*x1_2.*x2_3+p2.*x1_1.*x1_4.*x3_4_d+p2.*x1_1.*x3_4.*x1_4_d+p2.*x1_4.*x3_4.*x1_1_d+p2_d.*x1_1.*x1_4.*x3_4).*6.0-t3.*t4.*t10.*(p3.*x1_2.*x2_3-p2.*x1_1.*x1_4.*x3_4+1.0).*6.0;
if nargout > 1
    out2 = p5_d.*t5.*t6.*t7.*6.0+p4.*t4.*t11.*x1_1_d.*6.0+p4_d.*t4.*t11.*x1_1.*6.0-p4_d.*t3.*t8.*x1_1_d.*6.0-p5.*t5.*t7.^2.*x2_6_d.*2.0-p4.*t3.*t4.*t10.*x1_1.*6.0-p5.*t5.*t7.*t9.*x2_6_d.*4.0;
end
if nargout > 2
    t17 = p8.*x4_1;
    t12 = exp(-t17);
    t13 = p8.*x4_1_d;
    t14 = p8_d.*x4_1;
    t15 = t13+t14;
    t16 = t15.^2;
    t18 = x1_7_d-x2_5_d;
    t19 = x1_7-x2_5;
    out3 = p7.*t12.*t16.*t18.*-3.0+p7_d.*t12.*t15.*t18.*6.0-p7_d.*t12.*t16.*t19.*3.0+p7.*t12.*t15.*t16.*t19+p7.*p8_d.*t12.*t18.*x4_1_d.*6.0+p7_d.*p8_d.*t12.*t19.*x4_1_d.*6.0-p7.*p8_d.*t12.*t15.*t19.*x4_1_d.*6.0;
end
if nargout > 3
    t23 = p1.*x4_1_d;
    t24 = p1_d.*x4_1;
    t20 = t23+t24;
    t21 = t20.^2;
    t25 = p1.*x4_1;
    t22 = exp(-t25);
    out4 = t21.*t22.*x1_5_d.*3.0-t20.*t21.*t22.*x1_5-p1_d.*t22.*x1_5_d.*x4_1_d.*6.0+p1_d.*t20.*t22.*x1_5.*x4_1_d.*6.0;
end
if nargout > 4
    out5 = 0.0;
end


function [out1,out2,out3,out4,out5] = sym_sd_demo_rhs_1_4(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_RHS_1_4
%    [OUT1,OUT2,OUT3,OUT4,OUT5] = SYM_SD_DEMO_RHS_1_4(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:44

t2 = p1_d+x2_1_d;
t3 = t2.^2;
t4 = p1+x2_1;
t5 = x2_6_d.^2;
t6 = tanh(x2_6);
t12 = t6.^2;
t7 = t12-1.0;
t8 = 1.0./t4.^5;
t9 = t3.^2;
t10 = 1.0./t4.^4;
t11 = 1.0./t4.^3;
out1 = t3.*t11.*(p3.*x1_2_d.*x2_3_d.*-2.0-p3_d.*x1_2.*x2_3_d.*2.0-p3_d.*x2_3.*x1_2_d.*2.0+p2.*x1_1.*x1_4_d.*x3_4_d.*2.0+p2.*x1_4.*x1_1_d.*x3_4_d.*2.0+p2.*x3_4.*x1_1_d.*x1_4_d.*2.0+p2_d.*x1_1.*x1_4.*x3_4_d.*2.0+p2_d.*x1_1.*x3_4.*x1_4_d.*2.0+p2_d.*x1_4.*x3_4.*x1_1_d.*2.0).*-1.2e1+t8.*t9.*(p3.*x1_2.*x2_3-p2.*x1_1.*x1_4.*x3_4+1.0).*2.4e1+t2.*1.0./t4.^2.*(p3_d.*x1_2_d.*x2_3_d.*-6.0+p2.*x1_1_d.*x1_4_d.*x3_4_d.*6.0+p2_d.*x1_1.*x1_4_d.*x3_4_d.*6.0+p2_d.*x1_4.*x1_1_d.*x3_4_d.*6.0+p2_d.*x3_4.*x1_1_d.*x1_4_d.*6.0).*4.0+t2.*t3.*t10.*(-p3.*x1_2.*x2_3_d-p3.*x2_3.*x1_2_d-p3_d.*x1_2.*x2_3+p2.*x1_1.*x1_4.*x3_4_d+p2.*x1_1.*x3_4.*x1_4_d+p2.*x1_4.*x3_4.*x1_1_d+p2_d.*x1_1.*x1_4.*x3_4).*2.4e1-(p2_d.*x1_1_d.*x1_4_d.*x3_4_d.*2.4e1)./t4;
if nargout > 1
    t13 = t7.^2;
    t14 = t5.^2;
    out2 = p5.*t6.*t13.*t14.*1.6e1+p4.*t8.*t9.*x1_1.*2.4e1+p4_d.*t3.*t11.*x1_1_d.*2.4e1-p5_d.*t5.*t13.*x2_6_d.*8.0+p5.*t6.*t7.*t12.*t14.*8.0-p4.*t2.*t3.*t10.*x1_1_d.*2.4e1-p4_d.*t2.*t3.*t10.*x1_1.*2.4e1-p5_d.*t5.*t7.*t12.*x2_6_d.*1.6e1;
end
if nargout > 2
    t18 = p8.*x4_1_d;
    t19 = p8_d.*x4_1;
    t15 = t18+t19;
    t16 = t15.^2;
    t20 = p8.*x4_1;
    t17 = exp(-t20);
    t21 = x1_7-x2_5;
    t22 = x1_7_d-x2_5_d;
    t26 = p1.*x4_1_d;
    t27 = p1_d.*x4_1;
    t23 = t26+t27;
    t24 = t23.^2;
    t29 = p1.*x4_1;
    t25 = exp(-t29);
    t28 = x4_1_d.^2;
    out3 = p7_d.*t16.*t17.*t22.*-1.2e1-p7.*t16.^2.*t17.*t21+p7.*t15.*t16.*t17.*t22.*4.0+p7_d.*t15.*t16.*t17.*t21.*4.0+p7_d.*p8_d.*t17.*t22.*x4_1_d.*2.4e1-p7.*p8_d.^2.*t17.*t21.*t28.*1.2e1-p7.*p8_d.*t15.*t17.*t22.*x4_1_d.*2.4e1+p7.*p8_d.*t16.*t17.*t21.*x4_1_d.*1.2e1-p7_d.*p8_d.*t15.*t17.*t21.*x4_1_d.*2.4e1;
end
if nargout > 3
    out4 = t24.^2.*t25.*x1_5-t23.*t24.*t25.*x1_5_d.*4.0+p1_d.^2.*t25.*t28.*x1_5.*1.2e1-p1_d.*t24.*t25.*x1_5.*x4_1_d.*1.2e1+p1_d.*t23.*t25.*x1_5_d.*x4_1_d.*2.4e1;
end
if nargout > 4
    out5 = 0.0;
end


function [out1,out2,out3,out4,out5] = sym_sd_demo_rhs_1_5(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_RHS_1_5
%    [OUT1,OUT2,OUT3,OUT4,OUT5] = SYM_SD_DEMO_RHS_1_5(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:45

t2 = p1_d+x2_1_d;
t3 = t2.^2;
t4 = t3.^2;
t5 = p1+x2_1;
t6 = x2_6_d.^2;
t7 = t6.^2;
t8 = tanh(x2_6);
t14 = t8.^2;
t9 = t14-1.0;
t10 = t9.^2;
t11 = 1.0./t5.^6;
t12 = 1.0./t5.^5;
t13 = 1.0./t5.^4;
out1 = t3.*1.0./t5.^3.*(p3_d.*x1_2_d.*x2_3_d.*-6.0+p2.*x1_1_d.*x1_4_d.*x3_4_d.*6.0+p2_d.*x1_1.*x1_4_d.*x3_4_d.*6.0+p2_d.*x1_4.*x1_1_d.*x3_4_d.*6.0+p2_d.*x3_4.*x1_1_d.*x1_4_d.*6.0).*-2.0e1-t4.*t12.*(-p3.*x1_2.*x2_3_d-p3.*x2_3.*x1_2_d-p3_d.*x1_2.*x2_3+p2.*x1_1.*x1_4.*x3_4_d+p2.*x1_1.*x3_4.*x1_4_d+p2.*x1_4.*x3_4.*x1_1_d+p2_d.*x1_1.*x1_4.*x3_4).*1.2e2-t2.*t4.*t11.*(p3.*x1_2.*x2_3-p2.*x1_1.*x1_4.*x3_4+1.0).*1.2e2+t2.*t3.*t13.*(p3.*x1_2_d.*x2_3_d.*-2.0-p3_d.*x1_2.*x2_3_d.*2.0-p3_d.*x2_3.*x1_2_d.*2.0+p2.*x1_1.*x1_4_d.*x3_4_d.*2.0+p2.*x1_4.*x1_1_d.*x3_4_d.*2.0+p2.*x3_4.*x1_1_d.*x1_4_d.*2.0+p2_d.*x1_1.*x1_4.*x3_4_d.*2.0+p2_d.*x1_1.*x3_4.*x1_4_d.*2.0+p2_d.*x1_4.*x3_4.*x1_1_d.*2.0).*6.0e1+p2_d.*t2.*1.0./t5.^2.*x1_1_d.*x1_4_d.*x3_4_d.*1.2e2;
if nargout > 1
    out2 = p5_d.*t7.*t8.*t10.*8.0e1+p4.*t4.*t12.*x1_1_d.*1.2e2+p4_d.*t4.*t12.*x1_1.*1.2e2-p5.*t7.*t9.*t14.^2.*x2_6_d.*1.6e1+p5_d.*t7.*t8.*t9.*t14.*4.0e1-p4.*t2.*t4.*t11.*x1_1.*1.2e2-p5.*t7.*t9.*t10.*x2_6_d.*1.6e1-p5.*t7.*t10.*t14.*x2_6_d.*8.8e1-p4_d.*t2.*t3.*t13.*x1_1_d.*1.2e2;
end
if nargout > 2
    t19 = p8.*x4_1_d;
    t20 = p8_d.*x4_1;
    t15 = t19+t20;
    t16 = t15.^2;
    t17 = t16.^2;
    t21 = p8.*x4_1;
    t18 = exp(-t21);
    t22 = x1_7-x2_5;
    t23 = x1_7_d-x2_5_d;
    t24 = p8_d.^2;
    t25 = x4_1_d.^2;
    out3 = p7.*t17.*t18.*t23.*-5.0-p7_d.*t17.*t18.*t22.*5.0+p7.*t15.*t17.*t18.*t22-p7.*t18.*t23.*t24.*t25.*6.0e1+p7_d.*t15.*t16.*t18.*t23.*2.0e1-p7_d.*t18.*t22.*t24.*t25.*6.0e1+p7.*t15.*t18.*t22.*t24.*t25.*6.0e1+p7.*p8_d.*t16.*t18.*t23.*x4_1_d.*6.0e1-p7_d.*p8_d.*t15.*t18.*t23.*x4_1_d.*1.2e2+p7_d.*p8_d.*t16.*t18.*t22.*x4_1_d.*6.0e1-p7.*p8_d.*t15.*t16.*t18.*t22.*x4_1_d.*2.0e1;
end
if nargout > 3
    t30 = p1.*x4_1_d;
    t31 = p1_d.*x4_1;
    t26 = t30+t31;
    t27 = t26.^2;
    t28 = t27.^2;
    t32 = p1.*x4_1;
    t29 = exp(-t32);
    t33 = p1_d.^2;
    out4 = t28.*t29.*x1_5_d.*5.0-t26.*t28.*t29.*x1_5+t25.*t29.*t33.*x1_5_d.*6.0e1-t25.*t26.*t29.*t33.*x1_5.*6.0e1-p1_d.*t27.*t29.*x1_5_d.*x4_1_d.*6.0e1+p1_d.*t26.*t27.*t29.*x1_5.*x4_1_d.*2.0e1;
end
if nargout > 4
    out5 = 0.0;
end


function out1 = sym_sd_demo_tau_1_0(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_1_0
%    OUT1 = SYM_SD_DEMO_TAU_1_0(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:46

out1 = tau1;


function out1 = sym_sd_demo_tau_2_0(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_2_0
%    OUT1 = SYM_SD_DEMO_TAU_2_0(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:46

out1 = tau2;


function out1 = sym_sd_demo_tau_3_0(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_3_0
%    OUT1 = SYM_SD_DEMO_TAU_3_0(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:46

out1 = p5.*tau1.*x2_1.*x2_2+2.0;


function out1 = sym_sd_demo_tau_4_0(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_4_0
%    OUT1 = SYM_SD_DEMO_TAU_4_0(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:46

out1 = -1.0./(x1_1.*x2_3+1.0)+1.0;


function out1 = sym_sd_demo_tau_5_0(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_5_0
%    OUT1 = SYM_SD_DEMO_TAU_5_0(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:47

out1 = x4_1;


function out1 = sym_sd_demo_tau_6_0(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_6_0
%    OUT1 = SYM_SD_DEMO_TAU_6_0(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:47

out1 = x5_1;


function out1 = sym_sd_demo_tau_1_1(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_1_1
%    OUT1 = SYM_SD_DEMO_TAU_1_1(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:47

out1 = tau1_d;


function out1 = sym_sd_demo_tau_2_1(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_2_1
%    OUT1 = SYM_SD_DEMO_TAU_2_1(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:47

out1 = tau2_d;


function out1 = sym_sd_demo_tau_3_1(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_3_1
%    OUT1 = SYM_SD_DEMO_TAU_3_1(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:47

out1 = p5.*tau1.*x2_1.*x2_2_d+p5.*tau1.*x2_2.*x2_1_d+p5.*tau1_d.*x2_1.*x2_2+p5_d.*tau1.*x2_1.*x2_2;


function out1 = sym_sd_demo_tau_4_1(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_4_1
%    OUT1 = SYM_SD_DEMO_TAU_4_1(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:47

out1 = 1.0./(x1_1.*x2_3+1.0).^2.*(x1_1.*x2_3_d+x2_3.*x1_1_d);


function out1 = sym_sd_demo_tau_5_1(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_5_1
%    OUT1 = SYM_SD_DEMO_TAU_5_1(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:48

out1 = x4_1_d;


function out1 = sym_sd_demo_tau_6_1(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_6_1
%    OUT1 = SYM_SD_DEMO_TAU_6_1(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:48

out1 = x5_1_d;


function out1 = sym_sd_demo_tau_1_2(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_1_2
%    OUT1 = SYM_SD_DEMO_TAU_1_2(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:48

out1 = 0.0;


function out1 = sym_sd_demo_tau_2_2(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_2_2
%    OUT1 = SYM_SD_DEMO_TAU_2_2(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:48

out1 = 0.0;


function out1 = sym_sd_demo_tau_3_2(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_3_2
%    OUT1 = SYM_SD_DEMO_TAU_3_2(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:48

out1 = p5.*tau1.*x2_1_d.*x2_2_d.*2.0+p5.*tau1_d.*x2_1.*x2_2_d.*2.0+p5.*tau1_d.*x2_2.*x2_1_d.*2.0+p5_d.*tau1.*x2_1.*x2_2_d.*2.0+p5_d.*tau1.*x2_2.*x2_1_d.*2.0+p5_d.*tau1_d.*x2_1.*x2_2.*2.0;


function out1 = sym_sd_demo_tau_4_2(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_4_2
%    OUT1 = SYM_SD_DEMO_TAU_4_2(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:48

t2 = x1_1.*x2_3_d+x2_3.*x1_1_d;
t3 = x1_1.*x2_3;
t4 = t3+1.0;
out1 = t2.^2.*1.0./t4.^3.*-2.0+1.0./t4.^2.*x1_1_d.*x2_3_d.*2.0;


function out1 = sym_sd_demo_tau_5_2(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_5_2
%    OUT1 = SYM_SD_DEMO_TAU_5_2(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:49

out1 = 0.0;


function out1 = sym_sd_demo_tau_6_2(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_6_2
%    OUT1 = SYM_SD_DEMO_TAU_6_2(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:49

out1 = 0.0;


function out1 = sym_sd_demo_tau_1_3(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_1_3
%    OUT1 = SYM_SD_DEMO_TAU_1_3(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:49

out1 = 0.0;


function out1 = sym_sd_demo_tau_2_3(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_2_3
%    OUT1 = SYM_SD_DEMO_TAU_2_3(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:49

out1 = 0.0;


function out1 = sym_sd_demo_tau_3_3(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_3_3
%    OUT1 = SYM_SD_DEMO_TAU_3_3(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:49

out1 = p5.*tau1_d.*x2_1_d.*x2_2_d.*6.0+p5_d.*tau1.*x2_1_d.*x2_2_d.*6.0+p5_d.*tau1_d.*x2_1.*x2_2_d.*6.0+p5_d.*tau1_d.*x2_2.*x2_1_d.*6.0;


function out1 = sym_sd_demo_tau_4_3(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_4_3
%    OUT1 = SYM_SD_DEMO_TAU_4_3(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:50

t6 = x1_1.*x2_3_d;
t7 = x2_3.*x1_1_d;
t2 = t6+t7;
t3 = t2.^2;
t4 = x1_1.*x2_3;
t5 = t4+1.0;
out1 = t2.*t3.*1.0./t5.^4.*6.0-t2.*1.0./t5.^3.*x1_1_d.*x2_3_d.*1.2e1;


function out1 = sym_sd_demo_tau_5_3(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_5_3
%    OUT1 = SYM_SD_DEMO_TAU_5_3(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:50

out1 = 0.0;


function out1 = sym_sd_demo_tau_6_3(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_6_3
%    OUT1 = SYM_SD_DEMO_TAU_6_3(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:50

out1 = 0.0;


function out1 = sym_sd_demo_tau_1_4(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_1_4
%    OUT1 = SYM_SD_DEMO_TAU_1_4(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:50

out1 = 0.0;


function out1 = sym_sd_demo_tau_2_4(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_2_4
%    OUT1 = SYM_SD_DEMO_TAU_2_4(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:50

out1 = 0.0;


function out1 = sym_sd_demo_tau_3_4(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_3_4
%    OUT1 = SYM_SD_DEMO_TAU_3_4(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:50

out1 = p5_d.*tau1_d.*x2_1_d.*x2_2_d.*2.4e1;


function out1 = sym_sd_demo_tau_4_4(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_4_4
%    OUT1 = SYM_SD_DEMO_TAU_4_4(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:51

t6 = x1_1.*x2_3_d;
t7 = x2_3.*x1_1_d;
t2 = t6+t7;
t3 = t2.^2;
t4 = x1_1.*x2_3;
t5 = t4+1.0;
out1 = t3.^2.*1.0./t5.^5.*-2.4e1-1.0./t5.^3.*x1_1_d.^2.*x2_3_d.^2.*2.4e1+t3.*1.0./t5.^4.*x1_1_d.*x2_3_d.*7.2e1;


function out1 = sym_sd_demo_tau_5_4(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_5_4
%    OUT1 = SYM_SD_DEMO_TAU_5_4(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:51

out1 = 0.0;


function out1 = sym_sd_demo_tau_6_4(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_6_4
%    OUT1 = SYM_SD_DEMO_TAU_6_4(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:51

out1 = 0.0;


function out1 = sym_sd_demo_tau_1_5(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_1_5
%    OUT1 = SYM_SD_DEMO_TAU_1_5(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:51

out1 = 0.0;


function out1 = sym_sd_demo_tau_2_5(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_2_5
%    OUT1 = SYM_SD_DEMO_TAU_2_5(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:51

out1 = 0.0;


function out1 = sym_sd_demo_tau_3_5(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_3_5
%    OUT1 = SYM_SD_DEMO_TAU_3_5(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:51

out1 = 0.0;


function out1 = sym_sd_demo_tau_4_5(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_4_5
%    OUT1 = SYM_SD_DEMO_TAU_4_5(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:52

t7 = x1_1.*x2_3_d;
t8 = x2_3.*x1_1_d;
t2 = t7+t8;
t3 = t2.^2;
t4 = t3.^2;
t5 = x1_1.*x2_3;
t6 = t5+1.0;
out1 = t2.*t4.*1.0./t6.^6.*1.2e2+t2.*1.0./t6.^4.*x1_1_d.^2.*x2_3_d.^2.*3.6e2-t2.*t3.*1.0./t6.^5.*x1_1_d.*x2_3_d.*4.8e2;


function out1 = sym_sd_demo_tau_5_5(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_5_5
%    OUT1 = SYM_SD_DEMO_TAU_5_5(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:52

out1 = 0.0;


function out1 = sym_sd_demo_tau_6_5(x1_1,x2_1,x3_1,x4_1,x5_1,x1_2,x2_2,x3_2,x4_2,x5_2,x1_3,x2_3,x3_3,x4_3,x5_3,x1_4,x2_4,x3_4,x4_4,x5_4,x1_5,x2_5,x3_5,x4_5,x5_5,x1_6,x2_6,x3_6,x4_6,x5_6,x1_7,x2_7,x3_7,x4_7,x5_7,p1,p2,p3,p4,p5,p6,p7,p8,p9,tau1,tau2,x1_1_d,x2_1_d,x3_1_d,x4_1_d,x5_1_d,x1_2_d,x2_2_d,x3_2_d,x4_2_d,x5_2_d,x1_3_d,x2_3_d,x3_3_d,x4_3_d,x5_3_d,x1_4_d,x2_4_d,x3_4_d,x4_4_d,x5_4_d,x1_5_d,x2_5_d,x3_5_d,x4_5_d,x5_5_d,x1_6_d,x2_6_d,x3_6_d,x4_6_d,x5_6_d,x1_7_d,x2_7_d,x3_7_d,x4_7_d,x5_7_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p7_d,p8_d,p9_d,tau1_d,tau2_d)
%SYM_SD_DEMO_TAU_6_5
%    OUT1 = SYM_SD_DEMO_TAU_6_5(X1_1,X2_1,X3_1,X4_1,X5_1,X1_2,X2_2,X3_2,X4_2,X5_2,X1_3,X2_3,X3_3,X4_3,X5_3,X1_4,X2_4,X3_4,X4_4,X5_4,X1_5,X2_5,X3_5,X4_5,X5_5,X1_6,X2_6,X3_6,X4_6,X5_6,X1_7,X2_7,X3_7,X4_7,X5_7,P1,P2,P3,P4,P5,P6,P7,P8,P9,TAU1,TAU2,X1_1_D,X2_1_D,X3_1_D,X4_1_D,X5_1_D,X1_2_D,X2_2_D,X3_2_D,X4_2_D,X5_2_D,X1_3_D,X2_3_D,X3_3_D,X4_3_D,X5_3_D,X1_4_D,X2_4_D,X3_4_D,X4_4_D,X5_4_D,X1_5_D,X2_5_D,X3_5_D,X4_5_D,X5_5_D,X1_6_D,X2_6_D,X3_6_D,X4_6_D,X5_6_D,X1_7_D,X2_7_D,X3_7_D,X4_7_D,X5_7_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P7_D,P8_D,P9_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Jul-2019 15:41:52

out1 = 0.0;

