function varargout=sym_poscontrol(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=3;
   return
  case 'tp_del'
   varargout{1}=1;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_poscontrol_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_poscontrol_rhs_1_0(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_RHS_1_0
%    [OUT1,OUT2] = SYM_POSCONTROL_RHS_1_0(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:56

out1 = (K.*c.*(s0-s2))./2.0;
if nargout > 1
    out2 = (x1+x3-c.*s1-(K.*c.*(s0.*-2.0+s2+s4))./2.0)./(c+(K.*c.*(s0-s4))./2.0);
end


function [out1,out2] = sym_poscontrol_rhs_1_1(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_RHS_1_1
%    [OUT1,OUT2] = SYM_POSCONTROL_RHS_1_1(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:56

t2 = s0-s2;
out1 = (K.*c_d.*t2)./2.0+(K_d.*c.*t2)./2.0+(K.*c.*(s0_d-s2_d))./2.0;
if nargout > 1
    t7 = s0.*2.0;
    t3 = s2+s4-t7;
    t4 = s0-s4;
    t5 = (K.*c.*t4)./2.0;
    t6 = c+t5;
    out2 = -(-x1_d-x3_d+c.*s1_d+c_d.*s1+(K.*c.*(s0_d.*-2.0+s2_d+s4_d))./2.0+(K.*c_d.*t3)./2.0+(K_d.*c.*t3)./2.0)./t6-1.0./t6.^2.*(x1+x3-c.*s1-(K.*c.*t3)./2.0).*(c_d+(K.*c_d.*t4)./2.0+(K_d.*c.*t4)./2.0+(K.*c.*(s0_d-s4_d))./2.0);
end


function [out1,out2] = sym_poscontrol_rhs_1_2(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_RHS_1_2
%    [OUT1,OUT2] = SYM_POSCONTROL_RHS_1_2(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:56

t2 = s0_d-s2_d;
out1 = K.*c_d.*t2+K_d.*c.*t2+K_d.*c_d.*(s0-s2);
if nargout > 1
    t16 = s0_d.*2.0;
    t3 = s2_d+s4_d-t16;
    t4 = s0-s4;
    t5 = (K.*c.*t4)./2.0;
    t6 = c+t5;
    t10 = s0.*2.0;
    t7 = s2+s4-t10;
    t9 = s0_d-s4_d;
    t13 = (K.*c.*t9)./2.0;
    t14 = (K.*c_d.*t4)./2.0;
    t15 = (K_d.*c.*t4)./2.0;
    t8 = c_d+t13+t14+t15;
    t11 = x1+x3-c.*s1-(K.*c.*t7)./2.0;
    t12 = 1.0./t6.^2;
    out2 = -(c_d.*s1_d.*2.0+K.*c_d.*t3+K_d.*c.*t3+K_d.*c_d.*t7)./t6-t11.*t12.*(K.*c_d.*t9+K_d.*c.*t9+K_d.*c_d.*t4)+t8.*t12.*(-x1_d-x3_d+c.*s1_d+c_d.*s1+(K.*c.*t3)./2.0+(K.*c_d.*t7)./2.0+(K_d.*c.*t7)./2.0).*2.0+1.0./t6.^3.*t8.^2.*t11.*2.0;
end


function [out1,out2] = sym_poscontrol_rhs_1_3(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_RHS_1_3
%    [OUT1,OUT2] = SYM_POSCONTROL_RHS_1_3(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:57

out1 = K_d.*c_d.*(s0_d-s2_d).*3.0;
if nargout > 1
    t13 = s0_d.*2.0;
    t2 = s2_d+s4_d-t13;
    t3 = s0-s4;
    t4 = (K.*c.*t3)./2.0;
    t5 = c+t4;
    t14 = s0.*2.0;
    t6 = s2+s4-t14;
    t7 = s0_d-s4_d;
    t8 = (K.*c.*t7)./2.0;
    t9 = (K.*c_d.*t3)./2.0;
    t10 = (K_d.*c.*t3)./2.0;
    t11 = c_d+t8+t9+t10;
    t12 = t11.^2;
    t15 = 1.0./t5.^2;
    t16 = c.*s1_d;
    t17 = c_d.*s1;
    t18 = (K.*c.*t2)./2.0;
    t19 = (K.*c_d.*t6)./2.0;
    t20 = (K_d.*c.*t6)./2.0;
    t21 = t16+t17+t18+t19+t20-x1_d-x3_d;
    t22 = 1.0./t5.^3;
    t23 = K.*c_d.*t7;
    t24 = K_d.*c.*t7;
    t25 = K_d.*c_d.*t3;
    t26 = t23+t24+t25;
    t28 = c.*s1;
    t29 = (K.*c.*t6)./2.0;
    t27 = -t28-t29+x1+x3;
    out2 = t11.*t15.*(c_d.*s1_d.*2.0+K.*c_d.*t2+K_d.*c.*t2+K_d.*c_d.*t6).*3.0-t12.*t21.*t22.*6.0+t15.*t21.*t26.*3.0+t11.*t22.*t26.*t27.*6.0-(K_d.*c_d.*t2.*3.0)./t5-1.0./t5.^4.*t11.*t12.*t27.*6.0-K_d.*c_d.*t7.*t15.*t27.*3.0;
end


function [out1,out2] = sym_poscontrol_rhs_1_4(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_RHS_1_4
%    [OUT1,OUT2] = SYM_POSCONTROL_RHS_1_4(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:57

out1 = 0.0;
if nargout > 1
    t2 = s0-s4;
    t7 = s0_d-s4_d;
    t8 = (K.*c.*t7)./2.0;
    t9 = (K.*c_d.*t2)./2.0;
    t10 = (K_d.*c.*t2)./2.0;
    t3 = c_d+t8+t9+t10;
    t4 = t3.^2;
    t5 = (K.*c.*t2)./2.0;
    t6 = c+t5;
    t12 = s0.*2.0;
    t11 = s2+s4-t12;
    t14 = s0_d.*2.0;
    t13 = s2_d+s4_d-t14;
    t15 = c_d.*s1_d.*2.0;
    t16 = K.*c_d.*t13;
    t17 = K_d.*c.*t13;
    t18 = K_d.*c_d.*t11;
    t19 = t15+t16+t17+t18;
    t20 = 1.0./t6.^3;
    t21 = K.*c_d.*t7;
    t22 = K_d.*c.*t7;
    t23 = K_d.*c_d.*t2;
    t24 = t21+t22+t23;
    t33 = c.*s1;
    t34 = (K.*c.*t11)./2.0;
    t25 = -t33-t34+x1+x3;
    t26 = c.*s1_d;
    t27 = c_d.*s1;
    t28 = (K.*c.*t13)./2.0;
    t29 = (K.*c_d.*t11)./2.0;
    t30 = (K_d.*c.*t11)./2.0;
    t31 = t26+t27+t28+t29+t30-x1_d-x3_d;
    t32 = 1.0./t6.^4;
    t35 = 1.0./t6.^2;
    out2 = t20.*t24.^2.*t25.*6.0+t4.^2.*1.0./t6.^5.*t25.*2.4e1-t4.*t19.*t20.*1.2e1+t19.*t24.*t35.*6.0+t3.*t4.*t31.*t32.*2.4e1-t3.*t20.*t24.*t31.*2.4e1-t4.*t24.*t25.*t32.*3.6e1+K_d.*c_d.*t3.*t13.*t35.*1.2e1+K_d.*c_d.*t7.*t31.*t35.*1.2e1+K_d.*c_d.*t3.*t7.*t20.*t25.*2.4e1;
end


function [out1,out2] = sym_poscontrol_rhs_1_5(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_RHS_1_5
%    [OUT1,OUT2] = SYM_POSCONTROL_RHS_1_5(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:57

out1 = 0.0;
if nargout > 1
    t2 = s0-s4;
    t8 = s0_d-s4_d;
    t9 = (K.*c.*t8)./2.0;
    t10 = (K.*c_d.*t2)./2.0;
    t11 = (K_d.*c.*t2)./2.0;
    t3 = c_d+t9+t10+t11;
    t4 = t3.^2;
    t5 = t4.^2;
    t6 = (K.*c.*t2)./2.0;
    t7 = c+t6;
    t13 = s0.*2.0;
    t12 = s2+s4-t13;
    t15 = s0_d.*2.0;
    t14 = s2_d+s4_d-t15;
    t24 = K.*c_d.*t8;
    t25 = K_d.*c.*t8;
    t26 = K_d.*c_d.*t2;
    t16 = t24+t25+t26;
    t17 = c.*s1_d;
    t18 = c_d.*s1;
    t19 = (K.*c.*t14)./2.0;
    t20 = (K.*c_d.*t12)./2.0;
    t21 = (K_d.*c.*t12)./2.0;
    t22 = t17+t18+t19+t20+t21-x1_d-x3_d;
    t23 = 1.0./t7.^3;
    t27 = c_d.*s1_d.*2.0;
    t28 = K.*c_d.*t14;
    t29 = K_d.*c.*t14;
    t30 = K_d.*c_d.*t12;
    t31 = t27+t28+t29+t30;
    t32 = 1.0./t7.^4;
    t33 = t16.^2;
    t36 = c.*s1;
    t37 = (K.*c.*t12)./2.0;
    t34 = -t36-t37+x1+x3;
    t35 = 1.0./t7.^5;
    t38 = 1.0./t7.^2;
    out2 = t5.*t22.*t35.*-1.2e2-t22.*t23.*t33.*3.0e1+t3.*t4.*t31.*t32.*6.0e1-t3.*t16.*t23.*t31.*6.0e1+t4.*t16.*t22.*t32.*1.8e2-t3.*t32.*t33.*t34.*9.0e1-t3.*t5.*1.0./t7.^6.*t34.*1.2e2-K_d.*c_d.*t4.*t14.*t23.*6.0e1+K_d.*c_d.*t14.*t16.*t38.*3.0e1+K_d.*c_d.*t8.*t31.*t38.*3.0e1+t3.*t4.*t16.*t34.*t35.*2.4e2-K_d.*c_d.*t3.*t8.*t22.*t23.*1.2e2-K_d.*c_d.*t4.*t8.*t32.*t34.*1.8e2+K_d.*c_d.*t8.*t16.*t23.*t34.*6.0e1;
end


function out1 = sym_poscontrol_tau_1_0(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_1_0
%    OUT1 = SYM_POSCONTROL_TAU_1_0(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = tau0;


function out1 = sym_poscontrol_tau_2_0(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_2_0
%    OUT1 = SYM_POSCONTROL_TAU_2_0(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = s1;


function out1 = sym_poscontrol_tau_3_0(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_3_0
%    OUT1 = SYM_POSCONTROL_TAU_3_0(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = s1+tau0;


function out1 = sym_poscontrol_tau_1_1(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_1_1
%    OUT1 = SYM_POSCONTROL_TAU_1_1(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = tau0_d;


function out1 = sym_poscontrol_tau_2_1(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_2_1
%    OUT1 = SYM_POSCONTROL_TAU_2_1(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = s1_d;


function out1 = sym_poscontrol_tau_3_1(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_3_1
%    OUT1 = SYM_POSCONTROL_TAU_3_1(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = s1_d+tau0_d;


function out1 = sym_poscontrol_tau_1_2(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_1_2
%    OUT1 = SYM_POSCONTROL_TAU_1_2(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = 0.0;


function out1 = sym_poscontrol_tau_2_2(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_2_2
%    OUT1 = SYM_POSCONTROL_TAU_2_2(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:58

out1 = 0.0;


function out1 = sym_poscontrol_tau_3_2(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_3_2
%    OUT1 = SYM_POSCONTROL_TAU_3_2(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_1_3(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_1_3
%    OUT1 = SYM_POSCONTROL_TAU_1_3(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_2_3(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_2_3
%    OUT1 = SYM_POSCONTROL_TAU_2_3(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_3_3(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_3_3
%    OUT1 = SYM_POSCONTROL_TAU_3_3(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_1_4(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_1_4
%    OUT1 = SYM_POSCONTROL_TAU_1_4(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_2_4(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_2_4
%    OUT1 = SYM_POSCONTROL_TAU_2_4(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_3_4(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_3_4
%    OUT1 = SYM_POSCONTROL_TAU_3_4(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_1_5(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_1_5
%    OUT1 = SYM_POSCONTROL_TAU_1_5(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_2_5(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_2_5
%    OUT1 = SYM_POSCONTROL_TAU_2_5(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;


function out1 = sym_poscontrol_tau_3_5(x1,s1,x2,s2,x3,s3,x4,s4,tau0,s0,K,c,x1_d,s1_d,x2_d,s2_d,x3_d,s3_d,x4_d,s4_d,tau0_d,s0_d,K_d,c_d)
%SYM_POSCONTROL_TAU_3_5
%    OUT1 = SYM_POSCONTROL_TAU_3_5(X1,S1,X2,S2,X3,S3,X4,S4,TAU0,S0,K,C,X1_D,S1_D,X2_D,S2_D,X3_D,S3_D,X4_D,S4_D,TAU0_D,S0_D,K_D,C_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Oct-2019 00:54:59

out1 = 0.0;

