function C1phi1phi1phi2psi1 = sys_C1(in1,in2,in3,in4,in5,in6)
%SYS_C1
%    C1PHI1PHI1PHI2PSI1 = SYS_C1(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Feb-2017 15:51:58

C1phi1phi1phi2psi1 = [0.0;0.0;0.0];
