function Bphi1phi1psi0 = sys_B2(in1,in2,in3,in4,in5)
%SYS_B2
%    BPHI1PHI1PSI0 = SYS_B2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Feb-2017 15:51:55

Bphi1phi1psi0 = [0.0;0.0;0.0];
