function J2 = sys_J2(in1,in2,in3,in4)
%SYS_J2
%    J2 = SYS_J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Feb-2017 15:51:56

J2 = [0.0;0.0;0.0];
