function Bphi1phi1phi2 = sys_C(in1,in2,in3,in4,in5)
%SYS_C
%    BPHI1PHI1PHI2 = SYS_C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Feb-2017 15:51:56

par3 = in2(:,3);
phi01 = in3(1,:);
phi11 = in4(1,:);
phi21 = in5(1,:);
Bphi1phi1phi2 = [par3.*phi01.*phi11.*phi21.*-6.0;0.0;0.0];
