function Dphi1phi1phi2phi3phi4 = sys_E(in1,in2,in3,in4,in5,in6,in7)
%SYS_E
%    DPHI1PHI1PHI2PHI3PHI4 = SYS_E(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Feb-2017 15:51:58

Dphi1phi1phi2phi3phi4 = [0.0;0.0;0.0];
