function Dphi1phi1phi2phi3 = sys_D(in1,in2,in3,in4,in5,in6)
%SYS_D
%    DPHI1PHI1PHI2PHI3 = SYS_D(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Feb-2017 15:51:57

Dphi1phi1phi2phi3 = [0.0;0.0;0.0];
