function Bphi1phi1 = sys_B(in1,in2,in3,in4)
%SYS_B
%    BPHI1PHI1 = SYS_B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Feb-2017 15:51:55

par3 = in2(:,3);
par4 = in2(:,4);
par6 = in2(:,6);
phi01 = in3(1,:);
phi04 = in3(4,:);
phi11 = in4(1,:);
phi14 = in4(4,:);
xx1_1 = in1(1);
Bphi1phi1 = [par4.*phi04.*phi14.*2.0-par3.*phi01.*phi11.*xx1_1.*6.0;par6.*phi01.*phi11.*-2.0;0.0];
