function varargout=sym_nested(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=1;
   return
  case 'maxorder'
   varargout{1}=5;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_nested_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});



function out1 = sym_nested_rhs_1_0(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_RHS_1_0
%    OUT1 = SYM_NESTED_RHS_1_0(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:39

out1 = -x2;


function out1 = sym_nested_rhs_1_1(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_RHS_1_1
%    OUT1 = SYM_NESTED_RHS_1_1(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:43

out1 = -x2_dev;


function out1 = sym_nested_rhs_1_2(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_RHS_1_2
%    OUT1 = SYM_NESTED_RHS_1_2(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:45

out1 = 0.0;


function out1 = sym_nested_rhs_1_3(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_RHS_1_3
%    OUT1 = SYM_NESTED_RHS_1_3(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:46

out1 = 0.0;


function out1 = sym_nested_rhs_1_4(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_RHS_1_4
%    OUT1 = SYM_NESTED_RHS_1_4(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:46

out1 = 0.0;


function out1 = sym_nested_rhs_1_5(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_RHS_1_5
%    OUT1 = SYM_NESTED_RHS_1_5(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:47

out1 = 0.0;


function out1 = sym_nested_tau_1_0(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_TAU_1_0
%    OUT1 = SYM_NESTED_TAU_1_0(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:48

out1 = p+x1;


function out1 = sym_nested_tau_1_1(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_TAU_1_1
%    OUT1 = SYM_NESTED_TAU_1_1(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:49

out1 = p_dev+x1_dev;


function out1 = sym_nested_tau_1_2(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_TAU_1_2
%    OUT1 = SYM_NESTED_TAU_1_2(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:49

out1 = 0.0;


function out1 = sym_nested_tau_1_3(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_TAU_1_3
%    OUT1 = SYM_NESTED_TAU_1_3(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:49

out1 = 0.0;


function out1 = sym_nested_tau_1_4(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_TAU_1_4
%    OUT1 = SYM_NESTED_TAU_1_4(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:49

out1 = 0.0;


function out1 = sym_nested_tau_1_5(x1,x2,p,x1_dev,x2_dev,p_dev)
%SYM_NESTED_TAU_1_5
%    OUT1 = SYM_NESTED_TAU_1_5(X1,X2,P,X1_DEV,X2_DEV,P_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    09-Jun-2017 15:10:50

out1 = 0.0;

