function varargout=sym_hom_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_hom_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_hom_demo_rhs_1_0(x1_1,x2_1,x1_2,x2_2,q11,q12,q21,e1,e2,tau,x1_1_d,x2_1_d,x1_2_d,x2_2_d,q11_d,q12_d,q21_d,e1_d,e2_d,tau_d)
%SYM_HOM_DEMO_RHS_1_0
%    [OUT1,OUT2] = SYM_HOM_DEMO_RHS_1_0(X1_1,X2_1,X1_2,X2_2,Q11,Q12,Q21,E1,E2,TAU,X1_1_D,X2_1_D,X1_2_D,X2_2_D,Q11_D,Q12_D,Q21_D,E1_D,E2_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 13:28:45

t2 = exp(x1_2.*-4.0);
t3 = t2+1.0;
t4 = 1.0./t3;
out1 = e1-x1_1+q11.*t4-q12.*x2_2;
if nargout > 1
    out2 = e2-x2_1+q21.*t4;
end


function [out1,out2] = sym_hom_demo_rhs_1_1(x1_1,x2_1,x1_2,x2_2,q11,q12,q21,e1,e2,tau,x1_1_d,x2_1_d,x1_2_d,x2_2_d,q11_d,q12_d,q21_d,e1_d,e2_d,tau_d)
%SYM_HOM_DEMO_RHS_1_1
%    [OUT1,OUT2] = SYM_HOM_DEMO_RHS_1_1(X1_1,X2_1,X1_2,X2_2,Q11,Q12,Q21,E1,E2,TAU,X1_1_D,X2_1_D,X1_2_D,X2_2_D,Q11_D,Q12_D,Q21_D,E1_D,E2_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 13:28:45

t3 = x1_2.*4.0;
t2 = exp(-t3);
t4 = t2+1.0;
t5 = 1.0./t4;
t6 = 1.0./t4.^2;
out1 = e1_d-x1_1_d+q11_d.*t5-q12.*x2_2_d-q12_d.*x2_2+q11.*t2.*t6.*x1_2_d.*4.0;
if nargout > 1
    out2 = e2_d-x2_1_d+q21_d.*t5+q21.*t2.*t6.*x1_2_d.*4.0;
end


function [out1,out2] = sym_hom_demo_rhs_1_2(x1_1,x2_1,x1_2,x2_2,q11,q12,q21,e1,e2,tau,x1_1_d,x2_1_d,x1_2_d,x2_2_d,q11_d,q12_d,q21_d,e1_d,e2_d,tau_d)
%SYM_HOM_DEMO_RHS_1_2
%    [OUT1,OUT2] = SYM_HOM_DEMO_RHS_1_2(X1_1,X2_1,X1_2,X2_2,Q11,Q12,Q21,E1,E2,TAU,X1_1_D,X2_1_D,X1_2_D,X2_2_D,Q11_D,Q12_D,Q21_D,E1_D,E2_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 13:28:46

t3 = x1_2.*4.0;
t2 = exp(-t3);
t4 = t2+1.0;
t5 = 1.0./t4.^2;
t6 = x1_2_d.^2;
t7 = exp(x1_2.*-8.0);
t8 = 1.0./t4.^3;
out1 = q12_d.*x2_2_d.*-2.0-q11.*t2.*t5.*t6.*1.6e1+q11.*t6.*t7.*t8.*3.2e1+q11_d.*t2.*t5.*x1_2_d.*8.0;
if nargout > 1
    out2 = q21.*t2.*t5.*t6.*-1.6e1+q21.*t6.*t7.*t8.*3.2e1+q21_d.*t2.*t5.*x1_2_d.*8.0;
end


function [out1,out2] = sym_hom_demo_rhs_1_3(x1_1,x2_1,x1_2,x2_2,q11,q12,q21,e1,e2,tau,x1_1_d,x2_1_d,x1_2_d,x2_2_d,q11_d,q12_d,q21_d,e1_d,e2_d,tau_d)
%SYM_HOM_DEMO_RHS_1_3
%    [OUT1,OUT2] = SYM_HOM_DEMO_RHS_1_3(X1_1,X2_1,X1_2,X2_2,Q11,Q12,Q21,E1,E2,TAU,X1_1_D,X2_1_D,X1_2_D,X2_2_D,Q11_D,Q12_D,Q21_D,E1_D,E2_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 13:28:46

t2 = x1_2_d.^2;
t4 = x1_2.*4.0;
t3 = exp(-t4);
t5 = t3+1.0;
t6 = 1.0./t5.^2;
t9 = x1_2.*8.0;
t7 = exp(-t9);
t8 = 1.0./t5.^3;
t10 = exp(x1_2.*-1.2e1);
t11 = 1.0./t5.^4;
out1 = q11_d.*t2.*t3.*t6.*-4.8e1+q11_d.*t2.*t7.*t8.*9.6e1+q11.*t2.*t3.*t6.*x1_2_d.*6.4e1-q11.*t2.*t7.*t8.*x1_2_d.*3.84e2+q11.*t2.*t10.*t11.*x1_2_d.*3.84e2;
if nargout > 1
    out2 = q21_d.*t2.*t3.*t6.*-4.8e1+q21_d.*t2.*t7.*t8.*9.6e1+q21.*t2.*t3.*t6.*x1_2_d.*6.4e1-q21.*t2.*t7.*t8.*x1_2_d.*3.84e2+q21.*t2.*t10.*t11.*x1_2_d.*3.84e2;
end


function [out1,out2] = sym_hom_demo_rhs_1_4(x1_1,x2_1,x1_2,x2_2,q11,q12,q21,e1,e2,tau,x1_1_d,x2_1_d,x1_2_d,x2_2_d,q11_d,q12_d,q21_d,e1_d,e2_d,tau_d)
%SYM_HOM_DEMO_RHS_1_4
%    [OUT1,OUT2] = SYM_HOM_DEMO_RHS_1_4(X1_1,X2_1,X1_2,X2_2,Q11,Q12,Q21,E1,E2,TAU,X1_1_D,X2_1_D,X1_2_D,X2_2_D,Q11_D,Q12_D,Q21_D,E1_D,E2_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 13:28:47

t2 = x1_2_d.^2;
t5 = x1_2.*4.0;
t3 = exp(-t5);
t4 = t2.^2;
t6 = t3+1.0;
t7 = 1.0./t6.^2;
t12 = x1_2.*8.0;
t8 = exp(-t12);
t9 = 1.0./t6.^3;
t13 = x1_2.*1.2e1;
t10 = exp(-t13);
t11 = 1.0./t6.^4;
t14 = exp(x1_2.*-1.6e1);
t15 = 1.0./t6.^5;
out1 = q11.*t3.*t4.*t7.*-2.56e2+q11.*t4.*t8.*t9.*3.584e3-q11.*t4.*t10.*t11.*9.216e3+q11.*t4.*t14.*t15.*6.144e3+q11_d.*t2.*t3.*t7.*x1_2_d.*2.56e2-q11_d.*t2.*t8.*t9.*x1_2_d.*1.536e3+q11_d.*t2.*t10.*t11.*x1_2_d.*1.536e3;
if nargout > 1
    out2 = q21.*t3.*t4.*t7.*-2.56e2+q21.*t4.*t8.*t9.*3.584e3-q21.*t4.*t10.*t11.*9.216e3+q21.*t4.*t14.*t15.*6.144e3+q21_d.*t2.*t3.*t7.*x1_2_d.*2.56e2-q21_d.*t2.*t8.*t9.*x1_2_d.*1.536e3+q21_d.*t2.*t10.*t11.*x1_2_d.*1.536e3;
end


function [out1,out2] = sym_hom_demo_rhs_1_5(x1_1,x2_1,x1_2,x2_2,q11,q12,q21,e1,e2,tau,x1_1_d,x2_1_d,x1_2_d,x2_2_d,q11_d,q12_d,q21_d,e1_d,e2_d,tau_d)
%SYM_HOM_DEMO_RHS_1_5
%    [OUT1,OUT2] = SYM_HOM_DEMO_RHS_1_5(X1_1,X2_1,X1_2,X2_2,Q11,Q12,Q21,E1,E2,TAU,X1_1_D,X2_1_D,X1_2_D,X2_2_D,Q11_D,Q12_D,Q21_D,E1_D,E2_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 13:28:47

t2 = x1_2_d.^2;
t3 = t2.^2;
t5 = x1_2.*4.0;
t4 = exp(-t5);
t6 = t4+1.0;
t7 = 1.0./t6.^2;
t14 = x1_2.*8.0;
t8 = exp(-t14);
t9 = 1.0./t6.^3;
t15 = x1_2.*1.2e1;
t10 = exp(-t15);
t11 = 1.0./t6.^4;
t16 = x1_2.*1.6e1;
t12 = exp(-t16);
t13 = 1.0./t6.^5;
t17 = exp(x1_2.*-2.0e1);
t18 = 1.0./t6.^6;
out1 = q11_d.*t3.*t4.*t7.*-1.28e3+q11_d.*t3.*t8.*t9.*1.792e4-q11_d.*t3.*t10.*t11.*4.608e4+q11_d.*t3.*t12.*t13.*3.072e4+q11.*t3.*t4.*t7.*x1_2_d.*1.024e3-q11.*t3.*t8.*t9.*x1_2_d.*3.072e4+q11.*t3.*t10.*t11.*x1_2_d.*1.536e5-q11.*t3.*t12.*t13.*x1_2_d.*2.4576e5+q11.*t3.*t17.*t18.*x1_2_d.*1.2288e5;
if nargout > 1
    out2 = q21_d.*t3.*t4.*t7.*-1.28e3+q21_d.*t3.*t8.*t9.*1.792e4-q21_d.*t3.*t10.*t11.*4.608e4+q21_d.*t3.*t12.*t13.*3.072e4+q21.*t3.*t4.*t7.*x1_2_d.*1.024e3-q21.*t3.*t8.*t9.*x1_2_d.*3.072e4+q21.*t3.*t10.*t11.*x1_2_d.*1.536e5-q21.*t3.*t12.*t13.*x1_2_d.*2.4576e5+q21.*t3.*t17.*t18.*x1_2_d.*1.2288e5;
end

