function varargout=sym_minimal_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'mf_dxlength'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_minimal_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});



function [out_1,out_2] = sym_minimal_demo_rhs_1_0(x1,xp1,x2,xp2,tau,a,b,d,x1_dev,xp1_dev,x2_dev,xp2_dev,tau_dev,a_dev,b_dev,d_dev)
%SYM_MINIMAL_DEMO_RHS_1_0
%    [OUT_1,OUT_2] = SYM_MINIMAL_DEMO_RHS_1_0(X1,XP1,X2,XP2,TAU,A,B,D,X1_DEV,XP1_DEV,X2_DEV,XP2_DEV,TAU_DEV,A_DEV,B_DEV,D_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-May-2017 21:11:49

out_1 = xp1;
if nargout > 1
    t2 = x1.^2;
    out_2 = -a.*x1-d.*xp1-t2.*x1-b.*(x1-x2);
end


function [out_1,out_2] = sym_minimal_demo_rhs_1_1(x1,xp1,x2,xp2,tau,a,b,d,x1_dev,xp1_dev,x2_dev,xp2_dev,tau_dev,a_dev,b_dev,d_dev)
%SYM_MINIMAL_DEMO_RHS_1_1
%    [OUT_1,OUT_2] = SYM_MINIMAL_DEMO_RHS_1_1(X1,XP1,X2,XP2,TAU,A,B,D,X1_DEV,XP1_DEV,X2_DEV,XP2_DEV,TAU_DEV,A_DEV,B_DEV,D_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-May-2017 21:11:49

out_1 = xp1_dev;
if nargout > 1
    out_2 = -a.*x1_dev-a_dev.*x1-d.*xp1_dev-d_dev.*xp1-b.*(x1_dev-x2_dev)-b_dev.*(x1-x2)-x1.^2.*x1_dev.*3.0;
end


function [out_1,out_2] = sym_minimal_demo_rhs_1_2(x1,xp1,x2,xp2,tau,a,b,d,x1_dev,xp1_dev,x2_dev,xp2_dev,tau_dev,a_dev,b_dev,d_dev)
%SYM_MINIMAL_DEMO_RHS_1_2
%    [OUT_1,OUT_2] = SYM_MINIMAL_DEMO_RHS_1_2(X1,XP1,X2,XP2,TAU,A,B,D,X1_DEV,XP1_DEV,X2_DEV,XP2_DEV,TAU_DEV,A_DEV,B_DEV,D_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-May-2017 21:11:50

out_1 = 0.0;
if nargout > 1
    out_2 = a_dev.*x1_dev.*-2.0-d_dev.*xp1_dev.*2.0-b_dev.*(x1_dev-x2_dev).*2.0-x1.*x1_dev.^2.*6.0;
end


function [out_1,out_2] = sym_minimal_demo_rhs_1_3(x1,xp1,x2,xp2,tau,a,b,d,x1_dev,xp1_dev,x2_dev,xp2_dev,tau_dev,a_dev,b_dev,d_dev)
%SYM_MINIMAL_DEMO_RHS_1_3
%    [OUT_1,OUT_2] = SYM_MINIMAL_DEMO_RHS_1_3(X1,XP1,X2,XP2,TAU,A,B,D,X1_DEV,XP1_DEV,X2_DEV,XP2_DEV,TAU_DEV,A_DEV,B_DEV,D_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-May-2017 21:11:50

out_1 = 0.0;
if nargout > 1
    t2 = x1_dev.^2;
    out_2 = t2.*x1_dev.*-6.0;
end


function [out_1,out_2] = sym_minimal_demo_rhs_1_4(x1,xp1,x2,xp2,tau,a,b,d,x1_dev,xp1_dev,x2_dev,xp2_dev,tau_dev,a_dev,b_dev,d_dev)
%SYM_MINIMAL_DEMO_RHS_1_4
%    [OUT_1,OUT_2] = SYM_MINIMAL_DEMO_RHS_1_4(X1,XP1,X2,XP2,TAU,A,B,D,X1_DEV,XP1_DEV,X2_DEV,XP2_DEV,TAU_DEV,A_DEV,B_DEV,D_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-May-2017 21:11:50

out_1 = 0.0;
if nargout > 1
    out_2 = 0.0;
end


function [out_1,out_2] = sym_minimal_demo_rhs_1_5(x1,xp1,x2,xp2,tau,a,b,d,x1_dev,xp1_dev,x2_dev,xp2_dev,tau_dev,a_dev,b_dev,d_dev)
%SYM_MINIMAL_DEMO_RHS_1_5
%    [OUT_1,OUT_2] = SYM_MINIMAL_DEMO_RHS_1_5(X1,XP1,X2,XP2,TAU,A,B,D,X1_DEV,XP1_DEV,X2_DEV,XP2_DEV,TAU_DEV,A_DEV,B_DEV,D_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-May-2017 21:11:51

out_1 = 0.0;
if nargout > 1
    out_2 = 0.0;
end

