%% develop adjoint operator for optimization problems
clear
addpath('../../ddebiftool/',...
    '../../ddebiftool_extra_nmfm/',...
    '../../ddebiftool_extra_rotsym/',...
    '../../ddebiftool_utilities/',....
    '../../ddebiftool_extra_symbolic/');
