function varargout=sym_GyanSwarupNag_mf(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_GyanSwarupNag_mf_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_GyanSwarupNag_mf_rhs_1_0(x1,x2,x1tau,x2tau,tau)
%SYM_GYANSWARUPNAG_MF_RHS_1_0
%    [OUT1,OUT2] = SYM_GYANSWARUPNAG_MF_RHS_1_0(X1,X2,X1TAU,X2TAU,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Feb-2020 13:02:05

out1 = x1.*-5.0+x2-x1tau.*2.0+x2tau;
if nargout > 1
    out2 = x1.*2.0+x2.*6.0+x1tau.*4.0-x2tau;
end


function [out1,out2] = sym_GyanSwarupNag_mf_rhs_1_1(x1,x2,x1tau,x2tau,tau,x1_d,x2_d,x1tau_d,x2tau_d,tau_d)
%SYM_GYANSWARUPNAG_MF_RHS_1_1
%    [OUT1,OUT2] = SYM_GYANSWARUPNAG_MF_RHS_1_1(X1,X2,X1TAU,X2TAU,TAU,X1_D,X2_D,X1TAU_D,X2TAU_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Feb-2020 13:02:06

out1 = x1_d.*-5.0+x2_d-x1tau_d.*2.0+x2tau_d;
if nargout > 1
    out2 = x1_d.*2.0+x2_d.*6.0+x1tau_d.*4.0-x2tau_d;
end


function [out1,out2] = sym_GyanSwarupNag_mf_rhs_1_2(x1,x2,x1tau,x2tau,tau,x1_d,x2_d,x1tau_d,x2tau_d,x1_d_d,x2_d_d,x1tau_d_d,x2tau_d_d,tau_d,tau_d_d)
%SYM_GYANSWARUPNAG_MF_RHS_1_2
%    [OUT1,OUT2] = SYM_GYANSWARUPNAG_MF_RHS_1_2(X1,X2,X1TAU,X2TAU,TAU,X1_D,X2_D,X1TAU_D,X2TAU_D,X1_D_D,X2_D_D,X1TAU_D_D,X2TAU_D_D,TAU_D,TAU_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Feb-2020 13:02:06

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_GyanSwarupNag_mf_rhs_1_3(x1,x2,x1tau,x2tau,tau,x1_d,x2_d,x1tau_d,x2tau_d,x1_d_d,x2_d_d,x1tau_d_d,x2tau_d_d,x1_d_d_d,x2_d_d_d,x1tau_d_d_d,x2tau_d_d_d,tau_d,tau_d_d,tau_d_d_d)
%SYM_GYANSWARUPNAG_MF_RHS_1_3
%    [OUT1,OUT2] = SYM_GYANSWARUPNAG_MF_RHS_1_3(X1,X2,X1TAU,X2TAU,TAU,X1_D,X2_D,X1TAU_D,X2TAU_D,X1_D_D,X2_D_D,X1TAU_D_D,X2TAU_D_D,X1_D_D_D,X2_D_D_D,X1TAU_D_D_D,X2TAU_D_D_D,TAU_D,TAU_D_D,TAU_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Feb-2020 13:02:06

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_GyanSwarupNag_mf_rhs_1_4(x1,x2,x1tau,x2tau,tau,x1_d,x2_d,x1tau_d,x2tau_d,x1_d_d,x2_d_d,x1tau_d_d,x2tau_d_d,x1_d_d_d,x2_d_d_d,x1tau_d_d_d,x2tau_d_d_d,x1_d_d_d_d,x2_d_d_d_d,x1tau_d_d_d_d,x2tau_d_d_d_d,tau_d,tau_d_d,tau_d_d_d,tau_d_d_d_d)
%SYM_GYANSWARUPNAG_MF_RHS_1_4
%    [OUT1,OUT2] = SYM_GYANSWARUPNAG_MF_RHS_1_4(X1,X2,X1TAU,X2TAU,TAU,X1_D,X2_D,X1TAU_D,X2TAU_D,X1_D_D,X2_D_D,X1TAU_D_D,X2TAU_D_D,X1_D_D_D,X2_D_D_D,X1TAU_D_D_D,X2TAU_D_D_D,X1_D_D_D_D,X2_D_D_D_D,X1TAU_D_D_D_D,X2TAU_D_D_D_D,TAU_D,TAU_D_D,TAU_D_D_D,TAU_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Feb-2020 13:02:06

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_GyanSwarupNag_mf_rhs_1_5(x1,x2,x1tau,x2tau,tau,x1_d,x2_d,x1tau_d,x2tau_d,x1_d_d,x2_d_d,x1tau_d_d,x2tau_d_d,x1_d_d_d,x2_d_d_d,x1tau_d_d_d,x2tau_d_d_d,x1_d_d_d_d,x2_d_d_d_d,x1tau_d_d_d_d,x2tau_d_d_d_d,x1_d_d_d_d_d,x2_d_d_d_d_d,x1tau_d_d_d_d_d,x2tau_d_d_d_d_d,tau_d,tau_d_d,tau_d_d_d,tau_d_d_d_d,tau_d_d_d_d_d)
%SYM_GYANSWARUPNAG_MF_RHS_1_5
%    [OUT1,OUT2] = SYM_GYANSWARUPNAG_MF_RHS_1_5(X1,X2,X1TAU,X2TAU,TAU,X1_D,X2_D,X1TAU_D,X2TAU_D,X1_D_D,X2_D_D,X1TAU_D_D,X2TAU_D_D,X1_D_D_D,X2_D_D_D,X1TAU_D_D_D,X2TAU_D_D_D,X1_D_D_D_D,X2_D_D_D_D,X1TAU_D_D_D_D,X2TAU_D_D_D_D,X1_D_D_D_D_D,X2_D_D_D_D_D,X1TAU_D_D_D_D_D,X2TAU_D_D_D_D_D,TAU_D,TAU_D_D,TAU_D_D_D,TAU_D_D_D_D,TAU_D_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Feb-2020 13:02:07

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end

