function [funcstr,derivatives]=dde_sym2funcs(fs,xxs,ps,varargin)
%% create matlab code for r.h.s (and delays if needed) from symbolic expressions
%
% $Id$
%%
default={'svn_id','','write',true,'filename','sys','sd_delay',sym([])};
[options,pass_on]=dde_set_options(default,varargin,'pass_on');
%% extract function name from (optional) filename
[pth,funcname,ext]=fileparts(options.filename);
[fstr{1},df{1},v{1},q{1}]=dde_symdericode(fs,xxs,ps,[funcname,'_rhs'],pass_on{:});
if ~isempty(options.sd_delay)
    tp_del=true;
    tau=options.sd_delay;
    ntau=length(tau);
    [fstr{2},df{2},v{2},q{3}]=dde_symdericode(tau,xxs,ps,[funcname,'_tau'],'scalar',true,pass_on{:});
    [fstr{3},df{3},v{3}]=dde_sdmf_symdericode(fs,tau,xxs,ps,[funcname,'_combined'],pass_on{:});
    mf_dxlength=numel(v{3});
else
    ntau=size(xxs,2)-1;
    tp_del=false;
    mf_dxlength=0;
end
str=[fstr{:}];
derivatives=struct('df',df,'xx',xxs,'parameter',ps,'dx',v,'dp',q);
%% create full function (still string)
nl=sprintf('\n');
header=sprintf('function varargout=%s(action,varargin)',funcname);
comment=[...
    '%% Automatically generated with matlabFunction',nl,...
    '% ',options.svn_id,nl,...
    '%#ok<*DEFNU,*INUSD,*INUSL>',nl];
body=[...
    'switch action',nl,...
    '  case ''ntau''',nl,...
    '   varargout{1}=',num2str(ntau),';',nl,...
    '   return',nl,...
    '  case ''tp_del''',nl,...
    '   varargout{1}=',num2str(tp_del),';',nl,...
    '   return',nl,...    
    '  case ''mf_dxlength''',nl,...
    '   varargout{1}=',num2str(mf_dxlength),';',nl,...
    '   return',nl,...    
    'end',nl,...
    'ind=varargin{1};',nl,...
    'order=varargin{2};',nl,...
    'nout=varargin{3};',nl,...
    'f=str2func(sprintf(''',funcname,'_%s_%d_%d'',action,ind,order));',nl,...
    'varargout=cell(nout,1);',nl,...
    '[varargout{:}]=f(varargin{4:end});',nl,...
    nl];
funcstr=[header,nl,comment,nl,body,nl,str];
%% write to file if requested
if options.write
    if isempty(ext)
        ext='.m';
    end
    filename=fullfile(pth,[funcname,ext]);
    fid=fopen(filename,'w');
    if fid<=0
        error('dde_sym2funcs:perm','dde_sym2funcs: could not create function file %s',filename);
    end
    fwrite(fid,funcstr);
    fclose(fid);
end
