function varargout=sym_nested3(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=3;
   return
  case 'tp_del'
   varargout{1}=1;
   return
  case 'mf_dxlength'
   varargout{1}=6;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_nested3_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});



function out_1 = sym_nested3_rhs_1_0(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_RHS_1_0
%    OUT_1 = SYM_NESTED3_RHS_1_0(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:49

out_1 = -xx4;


function out_1 = sym_nested3_rhs_1_1(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_RHS_1_1
%    OUT_1 = SYM_NESTED3_RHS_1_1(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:49

out_1 = -xx4_dev;


function out_1 = sym_nested3_rhs_1_2(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_RHS_1_2
%    OUT_1 = SYM_NESTED3_RHS_1_2(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:49

out_1 = 0.0;


function out_1 = sym_nested3_rhs_1_3(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_RHS_1_3
%    OUT_1 = SYM_NESTED3_RHS_1_3(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:49

out_1 = 0.0;


function out_1 = sym_nested3_rhs_1_4(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_RHS_1_4
%    OUT_1 = SYM_NESTED3_RHS_1_4(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:50

out_1 = 0.0;


function out_1 = sym_nested3_rhs_1_5(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_RHS_1_5
%    OUT_1 = SYM_NESTED3_RHS_1_5(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:50

out_1 = 0.0;


function out = sym_nested3_tau_1_0(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_1_0
%    OUT = SYM_NESTED3_TAU_1_0(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:50

out = p1+xx1+p2.*xx1.^2;


function out = sym_nested3_tau_2_0(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_2_0
%    OUT = SYM_NESTED3_TAU_2_0(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:51

out = p1+xx2+p2.*xx2.^2;


function out = sym_nested3_tau_3_0(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_3_0
%    OUT = SYM_NESTED3_TAU_3_0(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:51

out = p1+xx3+p2.*xx3.^2;


function out = sym_nested3_tau_1_1(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_1_1
%    OUT = SYM_NESTED3_TAU_1_1(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:51

out = p1_dev+xx1_dev+p2_dev.*xx1.^2+p2.*xx1.*xx1_dev.*2.0;


function out = sym_nested3_tau_2_1(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_2_1
%    OUT = SYM_NESTED3_TAU_2_1(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:51

out = p1_dev+xx2_dev+p2_dev.*xx2.^2+p2.*xx2.*xx2_dev.*2.0;


function out = sym_nested3_tau_3_1(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_3_1
%    OUT = SYM_NESTED3_TAU_3_1(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:52

out = p1_dev+xx3_dev+p2_dev.*xx3.^2+p2.*xx3.*xx3_dev.*2.0;


function out = sym_nested3_tau_1_2(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_1_2
%    OUT = SYM_NESTED3_TAU_1_2(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:52

out = p2.*xx1_dev.^2.*2.0+p2_dev.*xx1.*xx1_dev.*4.0;


function out = sym_nested3_tau_2_2(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_2_2
%    OUT = SYM_NESTED3_TAU_2_2(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:52

out = p2.*xx2_dev.^2.*2.0+p2_dev.*xx2.*xx2_dev.*4.0;


function out = sym_nested3_tau_3_2(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_3_2
%    OUT = SYM_NESTED3_TAU_3_2(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:52

out = p2.*xx3_dev.^2.*2.0+p2_dev.*xx3.*xx3_dev.*4.0;


function out = sym_nested3_tau_1_3(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_1_3
%    OUT = SYM_NESTED3_TAU_1_3(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:52

out = p2_dev.*xx1_dev.^2.*6.0;


function out = sym_nested3_tau_2_3(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_2_3
%    OUT = SYM_NESTED3_TAU_2_3(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:53

out = p2_dev.*xx2_dev.^2.*6.0;


function out = sym_nested3_tau_3_3(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_3_3
%    OUT = SYM_NESTED3_TAU_3_3(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:53

out = p2_dev.*xx3_dev.^2.*6.0;


function out = sym_nested3_tau_1_4(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_1_4
%    OUT = SYM_NESTED3_TAU_1_4(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:53

out = 0.0;


function out = sym_nested3_tau_2_4(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_2_4
%    OUT = SYM_NESTED3_TAU_2_4(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:53

out = 0.0;


function out = sym_nested3_tau_3_4(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_3_4
%    OUT = SYM_NESTED3_TAU_3_4(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:53

out = 0.0;


function out = sym_nested3_tau_1_5(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_1_5
%    OUT = SYM_NESTED3_TAU_1_5(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:53

out = 0.0;


function out = sym_nested3_tau_2_5(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_2_5
%    OUT = SYM_NESTED3_TAU_2_5(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:54

out = 0.0;


function out = sym_nested3_tau_3_5(xx1,xx2,xx3,xx4,p1,p2,xx1_dev,xx2_dev,xx3_dev,xx4_dev,p1_dev,p2_dev)
%SYM_NESTED3_TAU_3_5
%    OUT = SYM_NESTED3_TAU_3_5(XX1,XX2,XX3,XX4,P1,P2,XX1_DEV,XX2_DEV,XX3_DEV,XX4_DEV,P1_DEV,P2_DEV)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:20:54

out = 0.0;


function out_1 = sym_nested3_combined_1_0(xx1,p1,p2,xx1_dev_0,xx1_dev_1,xx1_dev_2,xx1_dev_3,xx1_dev_4,xx1_dev_5)
%SYM_NESTED3_COMBINED_1_0
%    OUT_1 = SYM_NESTED3_COMBINED_1_0(XX1,P1,P2,XX1_DEV_0,XX1_DEV_1,XX1_DEV_2,XX1_DEV_3,XX1_DEV_4,XX1_DEV_5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:21:11

t2 = xx1(0.0);
t3 = t2.^2;
t6 = p2.*t3;
t4 = -p1-t2-t6;
t5 = xx1(t4);
t7 = t5.^2;
t8 = -p1-t5-p2.*t7;
t9 = xx1(t8);
out_1 = -xx1_dev_0(-p1-t9-p2.*t9.^2);


function out_1 = sym_nested3_combined_1_1(xx1,p1,p2,xx1_dev_0,xx1_dev_1,xx1_dev_2,xx1_dev_3,xx1_dev_4,xx1_dev_5)
%SYM_NESTED3_COMBINED_1_1
%    OUT_1 = SYM_NESTED3_COMBINED_1_1(XX1,P1,P2,XX1_DEV_0,XX1_DEV_1,XX1_DEV_2,XX1_DEV_3,XX1_DEV_4,XX1_DEV_5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:21:11

t2 = xx1(0.0);
t3 = t2.^2;
t6 = p2.*t3;
t4 = -p1-t2-t6;
t5 = xx1(t4);
t7 = t5.^2;
t8 = -p1-t5-p2.*t7;
t9 = xx1(t8);
out_1 = -xx1_dev_0(-p1-t9-p2.*t9.^2);


function out_1 = sym_nested3_combined_1_2(xx1,p1,p2,xx1_dev_0,xx1_dev_1,xx1_dev_2,xx1_dev_3,xx1_dev_4,xx1_dev_5)
%SYM_NESTED3_COMBINED_1_2
%    OUT_1 = SYM_NESTED3_COMBINED_1_2(XX1,P1,P2,XX1_DEV_0,XX1_DEV_1,XX1_DEV_2,XX1_DEV_3,XX1_DEV_4,XX1_DEV_5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:21:11

t2 = xx1(0.0);
t3 = t2.^2;
t6 = p2.*t3;
t4 = -p1-t2-t6;
t5 = xx1(t4);
t7 = t5.^2;
t10 = p2.*t7;
t8 = -p1-t5-t10;
t9 = xx1(t8);
t11 = xx1_dev_0(t8);
out_1 = xx1_dev_1(-p1-t9-p2.*t9.^2).*(t11+p2.*t9.*t11.*2.0).*2.0;


function out_1 = sym_nested3_combined_1_3(xx1,p1,p2,xx1_dev_0,xx1_dev_1,xx1_dev_2,xx1_dev_3,xx1_dev_4,xx1_dev_5)
%SYM_NESTED3_COMBINED_1_3
%    OUT_1 = SYM_NESTED3_COMBINED_1_3(XX1,P1,P2,XX1_DEV_0,XX1_DEV_1,XX1_DEV_2,XX1_DEV_3,XX1_DEV_4,XX1_DEV_5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:21:12

t2 = xx1(0.0);
t3 = t2.^2;
t6 = p2.*t3;
t4 = -p1-t2-t6;
t5 = xx1(t4);
t7 = t5.^2;
t10 = p2.*t7;
t8 = -p1-t5-t10;
t9 = xx1(t8);
t11 = xx1_dev_0(t4);
t12 = xx1_dev_0(t8);
t13 = xx1_dev_1(t8);
t14 = p2.*t5.*t11.*2.0;
t15 = t11+t14;
t16 = t9.^2;
t17 = -p1-t9-p2.*t16;
t18 = t12+p2.*t9.*t12.*2.0;
out_1 = t18.^2.*xx1_dev_2(t17).*-3.0-xx1_dev_1(t17).*(t13.*t15.*2.0-p2.*t12.^2.*2.0+p2.*t9.*t13.*t15.*4.0).*3.0;


function out_1 = sym_nested3_combined_1_4(xx1,p1,p2,xx1_dev_0,xx1_dev_1,xx1_dev_2,xx1_dev_3,xx1_dev_4,xx1_dev_5)
%SYM_NESTED3_COMBINED_1_4
%    OUT_1 = SYM_NESTED3_COMBINED_1_4(XX1,P1,P2,XX1_DEV_0,XX1_DEV_1,XX1_DEV_2,XX1_DEV_3,XX1_DEV_4,XX1_DEV_5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:21:13

t2 = xx1(0.0);
t3 = t2.^2;
t6 = p2.*t3;
t4 = -p1-t2-t6;
t5 = xx1(t4);
t7 = t5.^2;
t10 = p2.*t7;
t8 = -p1-t5-t10;
t9 = xx1(t8);
t11 = xx1_dev_0(t8);
t33 = p2.*t9.*t11.*2.0;
t12 = t11+t33;
t13 = t12.^2;
t14 = t9.^2;
t32 = p2.*t14;
t15 = -p1-t9-t32;
t16 = xx1_dev_0(0.0);
t17 = xx1_dev_0(t4);
t18 = xx1_dev_1(t4);
t19 = p2.*t2.*t16.*2.0;
t20 = t16+t19;
t29 = p2.*t5.*t17.*2.0;
t21 = t17+t29;
t22 = xx1_dev_1(t8);
t23 = t18.*t20.*2.0;
t24 = t17.^2;
t25 = p2.*t5.*t18.*t20.*4.0;
t26 = t23+t25-p2.*t24.*2.0;
t27 = t22.*t26.*3.0;
t28 = xx1_dev_2(t8);
t30 = t21.^2;
t31 = t28.*t30.*3.0;
out_1 = xx1_dev_1(t15).*(t27+t31+p2.*t9.*(t27+t31).*2.0-p2.*t11.*t21.*t22.*1.2e1).*4.0+t12.*t13.*xx1_dev_3(t15).*4.0+t12.*xx1_dev_2(t15).*(t21.*t22.*2.0-p2.*t11.^2.*2.0+p2.*t9.*t21.*t22.*4.0).*1.2e1;


function out_1 = sym_nested3_combined_1_5(xx1,p1,p2,xx1_dev_0,xx1_dev_1,xx1_dev_2,xx1_dev_3,xx1_dev_4,xx1_dev_5)
%SYM_NESTED3_COMBINED_1_5
%    OUT_1 = SYM_NESTED3_COMBINED_1_5(XX1,P1,P2,XX1_DEV_0,XX1_DEV_1,XX1_DEV_2,XX1_DEV_3,XX1_DEV_4,XX1_DEV_5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    05-Mar-2017 21:21:15

t2 = xx1(0.0);
t3 = t2.^2;
t6 = p2.*t3;
t4 = -p1-t2-t6;
t5 = xx1(t4);
t7 = t5.^2;
t10 = p2.*t7;
t8 = -p1-t5-t10;
t9 = xx1(t8);
t11 = xx1_dev_0(t4);
t12 = xx1_dev_0(t8);
t13 = xx1_dev_1(t8);
t14 = p2.*t5.*t11.*2.0;
t15 = t11+t14;
t50 = t13.*t15.*2.0;
t51 = t12.^2;
t52 = p2.*t51.*2.0;
t53 = p2.*t9.*t13.*t15.*4.0;
t16 = t50-t52+t53;
t17 = t9.^2;
t42 = p2.*t17;
t18 = -p1-t9-t42;
t19 = xx1_dev_0(0.0);
t22 = p2.*t2.*t19.*2.0;
t20 = t19+t22;
t21 = xx1_dev_2(t4);
t23 = t20.^2;
t24 = t21.*t23.*3.0;
t25 = xx1_dev_1(t4);
t26 = t19.^2;
t27 = t15.^2;
t28 = xx1_dev_2(t8);
t29 = t20.*t25.*2.0;
t30 = t11.^2;
t31 = p2.*t5.*t20.*t25.*4.0;
t38 = p2.*t30.*2.0;
t32 = t29+t31-t38;
t35 = p2.*t25.*t26.*6.0;
t33 = t24-t35;
t34 = p2.*t5.*t33.*2.0;
t36 = xx1_dev_3(t8);
t37 = t15.*t27.*t36.*4.0;
t39 = t15.*t28.*t32.*1.2e1;
t40 = t24+t34-t35-p2.*t11.*t20.*t25.*1.2e1;
t41 = t13.*t40.*4.0;
t46 = p2.*t9.*t12.*2.0;
t43 = t12+t46;
t44 = t43.^2;
t45 = xx1_dev_2(t18);
t47 = t13.*t32.*3.0;
t48 = t27.*t28.*3.0;
t49 = t47+t48;
out_1 = t44.^2.*xx1_dev_4(t18).*-5.0-t16.^2.*t45.*1.5e1-xx1_dev_1(t18).*(t37+t39+t41-p2.*t13.^2.*t27.*2.4e1-p2.*t12.*t49.*8.0+p2.*t9.*(t37+t39+t41).*2.0).*5.0-t16.*t44.*xx1_dev_3(t18).*3.0e1-t43.*t45.*(t47+t48+p2.*t9.*t49.*2.0-p2.*t12.*t13.*t15.*1.2e1).*2.0e1;

