function df=sys_dirderi(i,xx,par,dxx,dpar)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>
f=str2func(sprintf('sys_dirderi%d',i));
df=f(xx{:},par{:},dxx{:},dpar{:});


function out1 = sys_dirderi1(xx1_1,xx2_1,xx3_1,xx1_2,xx2_2,xx3_2,par1,par2,par3,par4,par5,par6,par7,par8,par9,v1_1,v2_1,v3_1,v1_2,v2_2,v3_2,q1,q2,q3,q4,q5,q6,q7,q8,q9)
%SYS_DIRDERI1
%    OUT1 = SYS_DIRDERI1(XX1_1,XX2_1,XX3_1,XX1_2,XX2_2,XX3_2,PAR1,PAR2,PAR3,PAR4,PAR5,PAR6,PAR7,PAR8,PAR9,V1_1,V2_1,V3_1,V1_2,V2_2,V3_2,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Mar-2017 00:16:26

t2 = xx1_1.^2;
t3 = par7-xx1_1;
out1 = [q1+v2_1-par5.*v3_1-q5.*xx3_1+q4.*xx1_2.^2-par3.*t2.*v1_1.*3.0-q3.*t2.*xx1_1+par4.*v1_2.*xx1_2.*2.0;q5-v2_1-q6.*t2-par6.*v1_1.*xx1_1.*2.0;-par8.*(v3_1+q2.*t3+par2.*(q7-v1_1))-q8.*(xx3_1+par2.*t3)];


function out1 = sys_dirderi2(xx1_1,xx2_1,xx3_1,xx1_2,xx2_2,xx3_2,par1,par2,par3,par4,par5,par6,par7,par8,par9,v1_1,v2_1,v3_1,v1_2,v2_2,v3_2,q1,q2,q3,q4,q5,q6,q7,q8,q9)
%SYS_DIRDERI2
%    OUT1 = SYS_DIRDERI2(XX1_1,XX2_1,XX3_1,XX1_2,XX2_2,XX3_2,PAR1,PAR2,PAR3,PAR4,PAR5,PAR6,PAR7,PAR8,PAR9,V1_1,V2_1,V3_1,V1_2,V2_2,V3_2,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Mar-2017 00:16:26

t2 = v1_1.^2;
t3 = q7-v1_1;
out1 = [q5.*v3_1.*-2.0+par4.*v1_2.^2.*2.0-q3.*v1_1.*xx1_1.^2.*6.0-par3.*t2.*xx1_1.*6.0+q4.*v1_2.*xx1_2.*4.0;par6.*t2.*-2.0-q6.*v1_1.*xx1_1.*4.0;q8.*(v3_1+par2.*t3+q2.*(par7-xx1_1)).*-2.0-par8.*q2.*t3.*2.0];


function out1 = sys_dirderi3(xx1_1,xx2_1,xx3_1,xx1_2,xx2_2,xx3_2,par1,par2,par3,par4,par5,par6,par7,par8,par9,v1_1,v2_1,v3_1,v1_2,v2_2,v3_2,q1,q2,q3,q4,q5,q6,q7,q8,q9)
%SYS_DIRDERI3
%    OUT1 = SYS_DIRDERI3(XX1_1,XX2_1,XX3_1,XX1_2,XX2_2,XX3_2,PAR1,PAR2,PAR3,PAR4,PAR5,PAR6,PAR7,PAR8,PAR9,V1_1,V2_1,V3_1,V1_2,V2_2,V3_2,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Mar-2017 00:16:26

t2 = v1_1.^2;
out1 = [q4.*v1_2.^2.*6.0-par3.*t2.*v1_1.*6.0-q3.*t2.*xx1_1.*1.8e1;q6.*t2.*-6.0;q2.*q8.*(q7-v1_1).*-6.0];


function out1 = sys_dirderi4(xx1_1,xx2_1,xx3_1,xx1_2,xx2_2,xx3_2,par1,par2,par3,par4,par5,par6,par7,par8,par9,v1_1,v2_1,v3_1,v1_2,v2_2,v3_2,q1,q2,q3,q4,q5,q6,q7,q8,q9)
%SYS_DIRDERI4
%    OUT1 = SYS_DIRDERI4(XX1_1,XX2_1,XX3_1,XX1_2,XX2_2,XX3_2,PAR1,PAR2,PAR3,PAR4,PAR5,PAR6,PAR7,PAR8,PAR9,V1_1,V2_1,V3_1,V1_2,V2_2,V3_2,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Mar-2017 00:16:27

t2 = v1_1.^2;
out1 = [q3.*t2.*v1_1.*-2.4e1;0.0;0.0];


function out1 = sys_dirderi5(xx1_1,xx2_1,xx3_1,xx1_2,xx2_2,xx3_2,par1,par2,par3,par4,par5,par6,par7,par8,par9,v1_1,v2_1,v3_1,v1_2,v2_2,v3_2,q1,q2,q3,q4,q5,q6,q7,q8,q9)
%SYS_DIRDERI5
%    OUT1 = SYS_DIRDERI5(XX1_1,XX2_1,XX3_1,XX1_2,XX2_2,XX3_2,PAR1,PAR2,PAR3,PAR4,PAR5,PAR6,PAR7,PAR8,PAR9,V1_1,V2_1,V3_1,V1_2,V2_2,V3_2,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Mar-2017 00:16:27

out1 = [0.0;0.0;0.0];

