function varargout=sym_cusp(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_cusp_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_cusp_rhs_1_0(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6)
%SYM_CUSP_RHS_1_0
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_0(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 12:34:27

t2 = exp(u1_2.*-4.0);
t3 = t2+1.0;
t4 = 1.0./t3;
t5 = t4-1.0./2.0;
out1 = p4-u1_1+p1.*t5-p2.*u2_2;
if nargout > 1
    out2 = p5-u2_1+p3.*t5;
end


function [out1,out2] = sym_cusp_rhs_1_1(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d)
%SYM_CUSP_RHS_1_1
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_1(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 12:34:27

t3 = u1_2.*4.0;
t2 = exp(-t3);
t4 = t2+1.0;
t5 = 1.0./t4;
t6 = t5-1.0./2.0;
t7 = 1.0./t4.^2;
out1 = p4_d-u1_1_d+p1_d.*t6-p2.*u2_2_d-p2_d.*u2_2+p1.*t2.*t7.*u1_2_d.*4.0;
if nargout > 1
    out2 = p5_d-u2_1_d+p3_d.*t6+p3.*t2.*t7.*u1_2_d.*4.0;
end


function [out1,out2] = sym_cusp_rhs_1_2(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d)
%SYM_CUSP_RHS_1_2
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_2(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 12:34:28

t3 = u1_2.*4.0;
t2 = exp(-t3);
t4 = t2+1.0;
t5 = 1.0./t4.^2;
t6 = exp(u1_2.*-8.0);
t7 = 1.0./t4.^3;
out1 = -p2_d.*u2_2_d_d-p2_d_d.*u2_2_d+p1_d.*t2.*t5.*u1_2_d_d.*4.0+p1_d_d.*t2.*t5.*u1_2_d.*4.0-p1.*t2.*t5.*u1_2_d.*u1_2_d_d.*1.6e1+p1.*t6.*t7.*u1_2_d.*u1_2_d_d.*3.2e1;
if nargout > 1
    out2 = p3_d.*t2.*t5.*u1_2_d_d.*4.0+p3_d_d.*t2.*t5.*u1_2_d.*4.0-p3.*t2.*t5.*u1_2_d.*u1_2_d_d.*1.6e1+p3.*t6.*t7.*u1_2_d.*u1_2_d_d.*3.2e1;
end


function [out1,out2] = sym_cusp_rhs_1_3(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,u1_1_d_d_d,u2_1_d_d_d,u1_2_d_d_d,u2_2_d_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d,p1_d_d_d,p2_d_d_d,p3_d_d_d,p4_d_d_d,p5_d_d_d,p6_d_d_d)
%SYM_CUSP_RHS_1_3
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_3(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,U1_1_D_D_D,U2_1_D_D_D,U1_2_D_D_D,U2_2_D_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D,P1_D_D_D,P2_D_D_D,P3_D_D_D,P4_D_D_D,P5_D_D_D,P6_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 12:34:28

t3 = u1_2.*4.0;
t2 = exp(-t3);
t4 = t2+1.0;
t5 = 1.0./t4.^2;
t8 = u1_2.*8.0;
t6 = exp(-t8);
t7 = 1.0./t4.^3;
t9 = exp(u1_2.*-1.2e1);
t10 = 1.0./t4.^4;
out1 = p1_d.*t2.*t5.*u1_2_d_d.*u1_2_d_d_d.*-1.6e1-p1_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d_d.*1.6e1-p1_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*1.6e1+p1_d.*t6.*t7.*u1_2_d_d.*u1_2_d_d_d.*3.2e1+p1_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d_d.*3.2e1+p1_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*3.2e1+p1.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e1-p1.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2+p1.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2;
if nargout > 1
    out2 = p3_d.*t2.*t5.*u1_2_d_d.*u1_2_d_d_d.*-1.6e1-p3_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d_d.*1.6e1-p3_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*1.6e1+p3_d.*t6.*t7.*u1_2_d_d.*u1_2_d_d_d.*3.2e1+p3_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d_d.*3.2e1+p3_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*3.2e1+p3.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e1-p3.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2+p3.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2;
end


function [out1,out2] = sym_cusp_rhs_1_4(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,u1_1_d_d_d,u2_1_d_d_d,u1_2_d_d_d,u2_2_d_d_d,u1_1_d_d_d_d,u2_1_d_d_d_d,u1_2_d_d_d_d,u2_2_d_d_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d,p1_d_d_d,p2_d_d_d,p3_d_d_d,p4_d_d_d,p5_d_d_d,p6_d_d_d,p1_d_d_d_d,p2_d_d_d_d,p3_d_d_d_d,p4_d_d_d_d,p5_d_d_d_d,p6_d_d_d_d)
%SYM_CUSP_RHS_1_4
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_4(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,U1_1_D_D_D,U2_1_D_D_D,U1_2_D_D_D,U2_2_D_D_D,U1_1_D_D_D_D,U2_1_D_D_D_D,U1_2_D_D_D_D,U2_2_D_D_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D,P1_D_D_D,P2_D_D_D,P3_D_D_D,P4_D_D_D,P5_D_D_D,P6_D_D_D,P1_D_D_D_D,P2_D_D_D_D,P3_D_D_D_D,P4_D_D_D_D,P5_D_D_D_D,P6_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 12:34:29

t3 = u1_2.*4.0;
t2 = exp(-t3);
t4 = t2+1.0;
t5 = 1.0./t4.^2;
t8 = u1_2.*8.0;
t6 = exp(-t8);
t7 = 1.0./t4.^3;
t11 = u1_2.*1.2e1;
t9 = exp(-t11);
t10 = 1.0./t4.^4;
t12 = exp(u1_2.*-1.6e1);
t13 = 1.0./t4.^5;
out1 = p1_d.*t2.*t5.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e1+p1_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e1+p1_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*6.4e1+p1_d_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e1-p1_d.*t6.*t7.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2-p1_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2-p1_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e2-p1_d_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2+p1_d.*t9.*t10.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2+p1_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2+p1_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e2+p1_d_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2-p1.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e2+p1.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e3-p1.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e3+p1.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e3;
if nargout > 1
    out2 = p3_d.*t2.*t5.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e1+p3_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e1+p3_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*6.4e1+p3_d_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e1-p3_d.*t6.*t7.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2-p3_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2-p3_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e2-p3_d_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2+p3_d.*t9.*t10.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2+p3_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e2+p3_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e2+p3_d_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e2-p3.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e2+p3.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e3-p3.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e3+p3.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e3;
end


function [out1,out2] = sym_cusp_rhs_1_5(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,u1_1_d_d_d,u2_1_d_d_d,u1_2_d_d_d,u2_2_d_d_d,u1_1_d_d_d_d,u2_1_d_d_d_d,u1_2_d_d_d_d,u2_2_d_d_d_d,u1_1_d_d_d_d_d,u2_1_d_d_d_d_d,u1_2_d_d_d_d_d,u2_2_d_d_d_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d,p1_d_d_d,p2_d_d_d,p3_d_d_d,p4_d_d_d,p5_d_d_d,p6_d_d_d,p1_d_d_d_d,p2_d_d_d_d,p3_d_d_d_d,p4_d_d_d_d,p5_d_d_d_d,p6_d_d_d_d,p1_d_d_d_d_d,p2_d_d_d_d_d,p3_d_d_d_d_d,p4_d_d_d_d_d,p5_d_d_d_d_d,p6_d_d_d_d_d)
%SYM_CUSP_RHS_1_5
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_5(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,U1_1_D_D_D,U2_1_D_D_D,U1_2_D_D_D,U2_2_D_D_D,U1_1_D_D_D_D,U2_1_D_D_D_D,U1_2_D_D_D_D,U2_2_D_D_D_D,U1_1_D_D_D_D_D,U2_1_D_D_D_D_D,U1_2_D_D_D_D_D,U2_2_D_D_D_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D,P1_D_D_D,P2_D_D_D,P3_D_D_D,P4_D_D_D,P5_D_D_D,P6_D_D_D,P1_D_D_D_D,P2_D_D_D_D,P3_D_D_D_D,P4_D_D_D_D,P5_D_D_D_D,P6_D_D_D_D,P1_D_D_D_D_D,P2_D_D_D_D_D,P3_D_D_D_D_D,P4_D_D_D_D_D,P5_D_D_D_D_D,P6_D_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 12:34:29

t3 = u1_2.*4.0;
t2 = exp(-t3);
t4 = t2+1.0;
t5 = 1.0./t4.^2;
t8 = u1_2.*8.0;
t6 = exp(-t8);
t7 = 1.0./t4.^3;
t11 = u1_2.*1.2e1;
t9 = exp(-t11);
t10 = 1.0./t4.^4;
t14 = u1_2.*1.6e1;
t12 = exp(-t14);
t13 = 1.0./t4.^5;
t15 = exp(u1_2.*-2.0e1);
t16 = 1.0./t4.^6;
out1 = p1_d.*t2.*t5.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*-2.56e2-p1_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e2-p1_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e2-p1_d_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*2.56e2-p1_d_d_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e2+p1_d.*t6.*t7.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p1_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p1_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p1_d_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p1_d_d_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e3-p1_d.*t9.*t10.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p1_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p1_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p1_d_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p1_d_d_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e3+p1_d.*t12.*t13.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p1_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p1_d_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p1_d_d_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p1_d_d_d_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e3+p1.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.024e3-p1.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.072e4+p1.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.536e5-p1.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.4576e5+p1.*t15.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.2288e5;
if nargout > 1
    out2 = p3_d.*t2.*t5.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*-2.56e2-p3_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e2-p3_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e2-p3_d_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*2.56e2-p3_d_d_d_d_d.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e2+p3_d.*t6.*t7.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p3_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p3_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p3_d_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*3.584e3+p3_d_d_d_d_d.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e3-p3_d.*t9.*t10.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p3_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p3_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p3_d_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*9.216e3-p3_d_d_d_d_d.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e3+p3_d.*t12.*t13.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p3_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p3_d_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p3_d_d_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*6.144e3+p3_d_d_d_d_d.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e3+p3.*t2.*t5.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.024e3-p3.*t6.*t7.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.072e4+p3.*t9.*t10.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.536e5-p3.*t12.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.4576e5+p3.*t15.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.2288e5;
end

