function varargout=sym_minimal_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_minimal_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_minimal_demo_rhs_1_0(x1,xp1,x2,xp2,tau,a,b,d,x1_d,xp1_d,x2_d,xp2_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_0
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_0(X1,XP1,X2,XP2,TAU,A,B,D,X1_D,XP1_D,X2_D,XP2_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Sep-2018 23:05:18

out1 = xp1;
if nargout > 1
    t2 = x1.^2;
    out2 = -a.*x1-d.*xp1-t2.*x1-b.*(x1-x2);
end


function [out1,out2] = sym_minimal_demo_rhs_1_1(x1,xp1,x2,xp2,tau,a,b,d,x1_d,xp1_d,x2_d,xp2_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_1
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_1(X1,XP1,X2,XP2,TAU,A,B,D,X1_D,XP1_D,X2_D,XP2_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Sep-2018 23:05:19

out1 = xp1_d;
if nargout > 1
    out2 = -a.*x1_d-a_d.*x1-d.*xp1_d-d_d.*xp1-b.*(x1_d-x2_d)-b_d.*(x1-x2)-x1.^2.*x1_d.*3.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_2(x1,xp1,x2,xp2,tau,a,b,d,x1_d,xp1_d,x2_d,xp2_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_2
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_2(X1,XP1,X2,XP2,TAU,A,B,D,X1_D,XP1_D,X2_D,XP2_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Sep-2018 23:05:19

out1 = 0.0;
if nargout > 1
    out2 = a_d.*x1_d.*-2.0-d_d.*xp1_d.*2.0-b_d.*(x1_d-x2_d).*2.0-x1.*x1_d.^2.*6.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_3(x1,xp1,x2,xp2,tau,a,b,d,x1_d,xp1_d,x2_d,xp2_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_3
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_3(X1,XP1,X2,XP2,TAU,A,B,D,X1_D,XP1_D,X2_D,XP2_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Sep-2018 23:05:19

out1 = 0.0;
if nargout > 1
    t2 = x1_d.^2;
    out2 = t2.*x1_d.*-6.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_4(x1,xp1,x2,xp2,tau,a,b,d,x1_d,xp1_d,x2_d,xp2_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_4
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_4(X1,XP1,X2,XP2,TAU,A,B,D,X1_D,XP1_D,X2_D,XP2_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Sep-2018 23:05:19

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_5(x1,xp1,x2,xp2,tau,a,b,d,x1_d,xp1_d,x2_d,xp2_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_5
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_5(X1,XP1,X2,XP2,TAU,A,B,D,X1_D,XP1_D,X2_D,XP2_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Sep-2018 23:05:19

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end

