function varargout=sym_minimal_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_minimal_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_minimal_demo_rhs_1_0(x,xp,xt,xpt,tau,a,b,d,x_d,xp_d,xt_d,xpt_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_0
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_0(X,XP,XT,XPT,TAU,A,B,D,X_D,XP_D,XT_D,XPT_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 09:12:38

out1 = xp;
if nargout > 1
    t2 = x.^2;
    out2 = -a.*x-d.*xp-t2.*x-b.*(x-xt);
end


function [out1,out2] = sym_minimal_demo_rhs_1_1(x,xp,xt,xpt,tau,a,b,d,x_d,xp_d,xt_d,xpt_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_1
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_1(X,XP,XT,XPT,TAU,A,B,D,X_D,XP_D,XT_D,XPT_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 09:12:38

out1 = xp_d;
if nargout > 1
    out2 = -a.*x_d-a_d.*x-d.*xp_d-d_d.*xp-b_d.*(x-xt)-b.*(x_d-xt_d)-x.^2.*x_d.*3.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_2(x,xp,xt,xpt,tau,a,b,d,x_d,xp_d,xt_d,xpt_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_2
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_2(X,XP,XT,XPT,TAU,A,B,D,X_D,XP_D,XT_D,XPT_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 09:12:38

out1 = 0.0;
if nargout > 1
    out2 = a_d.*x_d.*-2.0-d_d.*xp_d.*2.0-b_d.*(x_d-xt_d).*2.0-x.*x_d.^2.*6.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_3(x,xp,xt,xpt,tau,a,b,d,x_d,xp_d,xt_d,xpt_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_3
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_3(X,XP,XT,XPT,TAU,A,B,D,X_D,XP_D,XT_D,XPT_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 09:12:39

out1 = 0.0;
if nargout > 1
    t2 = x_d.^2;
    out2 = t2.*x_d.*-6.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_4(x,xp,xt,xpt,tau,a,b,d,x_d,xp_d,xt_d,xpt_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_4
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_4(X,XP,XT,XPT,TAU,A,B,D,X_D,XP_D,XT_D,XPT_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 09:12:39

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_minimal_demo_rhs_1_5(x,xp,xt,xpt,tau,a,b,d,x_d,xp_d,xt_d,xpt_d,tau_d,a_d,b_d,d_d)
%SYM_MINIMAL_DEMO_RHS_1_5
%    [OUT1,OUT2] = SYM_MINIMAL_DEMO_RHS_1_5(X,XP,XT,XPT,TAU,A,B,D,X_D,XP_D,XT_D,XPT_D,TAU_D,A_D,B_D,D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Feb-2019 09:12:39

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end

