hold on;
pl_hopf_branch1 = plot(getpars(hopf_branch1.point,ind.c),...
    getpars(hopf_branch1.point,ind.a),'color',cm(1,:));
plot(getpars(hopf_branch2.point,ind.c),...
    getpars(hopf_branch2.point,ind.a),'color',cm(1,:));
pl_hoho=plot(getpars(hopf_branch1.point(hoho_ind_br1),ind.c),...
    getpars(hopf_branch1.point(hoho_ind_br1),ind.a),'ko','MarkerSize',6);
plot(getpars(hopf_branch2.point(hoho_ind_br2),ind.c),...
    getpars(hopf_branch2.point(hoho_ind_br2),ind.a),'ko','MarkerSize',6);
pl_genh=plot(getpars(hopf_branch1.point(genh_ind_br1),ind.c),...
    getpars(hopf_branch1.point(genh_ind_br1),ind.a),'bd','MarkerSize',6);
plot(getpars(hopf_branch2.point(genh_ind_br1),ind.c),...
    getpars(hopf_branch2.point(genh_ind_br1),ind.a),'bd','MarkerSize',6);
plot(getpars(hopf_branch1.point(zeho_ind_br1),ind.c),...
    getpars(hopf_branch1.point(zeho_ind_br1),ind.a),'rs','MarkerSize',6);
pl_zeho=plot(getpars(hopf_branch2.point(zeho_ind_br2),ind.c),...
    getpars(hopf_branch2.point(zeho_ind_br2),ind.a),'rs','MarkerSize',6);
xlabel('$c$','Interpreter','LaTex');
ylabel('$a$','Interpreter','LaTex');
HH1=hopf_branch1.point(hoho_ind_br1(2));
hh1_text=text(HH1.parameter(ind.c)+0.01,HH1.parameter(ind.a)+0.01,'$HH_1$',...
    'Interpreter','LaTex');
HH2=hopf_branch1.point(hoho_ind_br1(3));
hh2_text=text(HH2.parameter(ind.c)+0.01,HH2.parameter(ind.a)+0.01,'$HH_2$',...
    'Interpreter','LaTex');