function varargout=sym_neuron(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_neuron_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_neuron_rhs_1_0(x1,x2,x1tau1,x2tau1,x1tau2,x2tau2,a,b,c,d,tau1,tau2,x1_d,x2_d,x1tau1_d,x2tau1_d,x1tau2_d,x2tau2_d,a_d,b_d,c_d,d_d,tau1_d,tau2_d)
%SYM_NEURON_RHS_1_0
%    [OUT1,OUT2] = SYM_NEURON_RHS_1_0(X1,X2,X1TAU1,X2TAU1,X1TAU2,X2TAU2,A,B,C,D,TAU1,TAU2,X1_D,X2_D,X1TAU1_D,X2TAU1_D,X1TAU2_D,X2TAU2_D,A_D,B_D,C_D,D_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Feb-2019 07:59:47

out1 = -x1-a.*(tanh(b.*x1tau1-1.0).*2.381097845541816+1.81343020392351)+c.*(tanh(d.*x2tau2-1.0).*2.381097845541816+1.81343020392351);
if nargout > 1
    out2 = -x2-a.*(tanh(b.*x2tau1-1.0).*2.381097845541816+1.81343020392351)+c.*(tanh(d.*x1tau2-1.0).*2.381097845541816+1.81343020392351);
end


function [out1,out2] = sym_neuron_rhs_1_1(x1,x2,x1tau1,x2tau1,x1tau2,x2tau2,a,b,c,d,tau1,tau2,x1_d,x2_d,x1tau1_d,x2tau1_d,x1tau2_d,x2tau2_d,a_d,b_d,c_d,d_d,tau1_d,tau2_d)
%SYM_NEURON_RHS_1_1
%    [OUT1,OUT2] = SYM_NEURON_RHS_1_1(X1,X2,X1TAU1,X2TAU1,X1TAU2,X2TAU2,A,B,C,D,TAU1,TAU2,X1_D,X2_D,X1TAU1_D,X2TAU1_D,X1TAU2_D,X2TAU2_D,A_D,B_D,C_D,D_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Feb-2019 07:59:47

t2 = b.*x1tau1;
t3 = t2-1.0;
t4 = tanh(t3);
t5 = d.*x2tau2;
t6 = t5-1.0;
t7 = tanh(t6);
out1 = -x1_d-a_d.*(t4.*2.381097845541816+1.81343020392351)+c_d.*(t7.*2.381097845541816+1.81343020392351)+a.*(t4.^2-1.0).*(b.*x1tau1_d+b_d.*x1tau1).*2.381097845541816-c.*(t7.^2-1.0).*(d.*x2tau2_d+d_d.*x2tau2).*2.381097845541816;
if nargout > 1
    t8 = b.*x2tau1;
    t9 = t8-1.0;
    t10 = tanh(t9);
    t11 = d.*x1tau2;
    t12 = t11-1.0;
    t13 = tanh(t12);
    out2 = -x2_d-a_d.*(t10.*2.381097845541816+1.81343020392351)+c_d.*(t13.*2.381097845541816+1.81343020392351)+a.*(t10.^2-1.0).*(b.*x2tau1_d+b_d.*x2tau1).*2.381097845541816-c.*(t13.^2-1.0).*(d.*x1tau2_d+d_d.*x1tau2).*2.381097845541816;
end


function [out1,out2] = sym_neuron_rhs_1_2(x1,x2,x1tau1,x2tau1,x1tau2,x2tau2,a,b,c,d,tau1,tau2,x1_d,x2_d,x1tau1_d,x2tau1_d,x1tau2_d,x2tau2_d,a_d,b_d,c_d,d_d,tau1_d,tau2_d)
%SYM_NEURON_RHS_1_2
%    [OUT1,OUT2] = SYM_NEURON_RHS_1_2(X1,X2,X1TAU1,X2TAU1,X1TAU2,X2TAU2,A,B,C,D,TAU1,TAU2,X1_D,X2_D,X1TAU1_D,X2TAU1_D,X1TAU2_D,X2TAU2_D,A_D,B_D,C_D,D_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Feb-2019 07:59:47

t4 = b.*x1tau1;
t5 = t4-1.0;
t2 = tanh(t5);
t8 = d.*x2tau2;
t9 = t8-1.0;
t3 = tanh(t9);
t6 = t2.^2;
t7 = t6-1.0;
t10 = t3.^2;
t11 = t10-1.0;
t12 = b.*x1tau1_d;
t13 = b_d.*x1tau1;
t14 = t12+t13;
t15 = d.*x2tau2_d;
t16 = d_d.*x2tau2;
t17 = t15+t16;
out1 = a_d.*t7.*t14.*4.762195691083632-c_d.*t11.*t17.*4.762195691083632+a.*b_d.*t7.*x1tau1_d.*4.762195691083632-c.*d_d.*t11.*x2tau2_d.*4.762195691083632-a.*t2.*t7.*t14.^2.*4.762195691083632+c.*t3.*t11.*t17.^2.*4.762195691083632;
if nargout > 1
    t20 = b.*x2tau1;
    t21 = t20-1.0;
    t18 = tanh(t21);
    t24 = d.*x1tau2;
    t25 = t24-1.0;
    t19 = tanh(t25);
    t22 = t18.^2;
    t23 = t22-1.0;
    t26 = t19.^2;
    t27 = t26-1.0;
    t28 = b.*x2tau1_d;
    t29 = b_d.*x2tau1;
    t30 = t28+t29;
    t31 = d.*x1tau2_d;
    t32 = d_d.*x1tau2;
    t33 = t31+t32;
    out2 = a_d.*t23.*t30.*4.762195691083632-c_d.*t27.*t33.*4.762195691083632+a.*b_d.*t23.*x2tau1_d.*4.762195691083632-c.*d_d.*t27.*x1tau2_d.*4.762195691083632-a.*t18.*t23.*t30.^2.*4.762195691083632+c.*t19.*t27.*t33.^2.*4.762195691083632;
end


function [out1,out2] = sym_neuron_rhs_1_3(x1,x2,x1tau1,x2tau1,x1tau2,x2tau2,a,b,c,d,tau1,tau2,x1_d,x2_d,x1tau1_d,x2tau1_d,x1tau2_d,x2tau2_d,a_d,b_d,c_d,d_d,tau1_d,tau2_d)
%SYM_NEURON_RHS_1_3
%    [OUT1,OUT2] = SYM_NEURON_RHS_1_3(X1,X2,X1TAU1,X2TAU1,X1TAU2,X2TAU2,A,B,C,D,TAU1,TAU2,X1_D,X2_D,X1TAU1_D,X2TAU1_D,X1TAU2_D,X2TAU2_D,A_D,B_D,C_D,D_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Feb-2019 07:59:48

t10 = b.*x1tau1;
t11 = t10-1.0;
t2 = tanh(t11);
t12 = t2.^2;
t3 = t12-1.0;
t13 = b.*x1tau1_d;
t14 = b_d.*x1tau1;
t4 = t13+t14;
t5 = t4.^2;
t15 = d.*x2tau2;
t16 = t15-1.0;
t6 = tanh(t16);
t17 = t6.^2;
t7 = t17-1.0;
t18 = d.*x2tau2_d;
t19 = d_d.*x2tau2;
t8 = t18+t19;
t9 = t8.^2;
out1 = a_d.*b_d.*t3.*x1tau1_d.*1.42865870732509e1-c_d.*d_d.*t7.*x2tau2_d.*1.42865870732509e1-a_d.*t2.*t3.*t5.*1.42865870732509e1+c_d.*t6.*t7.*t9.*1.42865870732509e1+a.*t3.^2.*t4.*t5.*4.762195691083632-c.*t7.^2.*t8.*t9.*4.762195691083632+a.*t3.*t4.*t5.*t12.*9.524391382167265-c.*t7.*t8.*t9.*t17.*9.524391382167265-a.*b_d.*t2.*t3.*t4.*x1tau1_d.*2.857317414650179e1+c.*d_d.*t6.*t7.*t8.*x2tau2_d.*2.857317414650179e1;
if nargout > 1
    t28 = b.*x2tau1;
    t29 = t28-1.0;
    t20 = tanh(t29);
    t30 = t20.^2;
    t21 = t30-1.0;
    t31 = b.*x2tau1_d;
    t32 = b_d.*x2tau1;
    t22 = t31+t32;
    t23 = t22.^2;
    t33 = d.*x1tau2;
    t34 = t33-1.0;
    t24 = tanh(t34);
    t35 = t24.^2;
    t25 = t35-1.0;
    t36 = d.*x1tau2_d;
    t37 = d_d.*x1tau2;
    t26 = t36+t37;
    t27 = t26.^2;
    out2 = a_d.*b_d.*t21.*x2tau1_d.*1.42865870732509e1-c_d.*d_d.*t25.*x1tau2_d.*1.42865870732509e1-a_d.*t20.*t21.*t23.*1.42865870732509e1+c_d.*t24.*t25.*t27.*1.42865870732509e1+a.*t21.^2.*t22.*t23.*4.762195691083632-c.*t25.^2.*t26.*t27.*4.762195691083632+a.*t21.*t22.*t23.*t30.*9.524391382167265-c.*t25.*t26.*t27.*t35.*9.524391382167265-a.*b_d.*t20.*t21.*t22.*x2tau1_d.*2.857317414650179e1+c.*d_d.*t24.*t25.*t26.*x1tau2_d.*2.857317414650179e1;
end


function [out1,out2] = sym_neuron_rhs_1_4(x1,x2,x1tau1,x2tau1,x1tau2,x2tau2,a,b,c,d,tau1,tau2,x1_d,x2_d,x1tau1_d,x2tau1_d,x1tau2_d,x2tau2_d,a_d,b_d,c_d,d_d,tau1_d,tau2_d)
%SYM_NEURON_RHS_1_4
%    [OUT1,OUT2] = SYM_NEURON_RHS_1_4(X1,X2,X1TAU1,X2TAU1,X1TAU2,X2TAU2,A,B,C,D,TAU1,TAU2,X1_D,X2_D,X1TAU1_D,X2TAU1_D,X1TAU2_D,X2TAU2_D,A_D,B_D,C_D,D_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Feb-2019 07:59:49

t10 = b.*x1tau1;
t11 = t10-1.0;
t2 = tanh(t11);
t12 = t2.^2;
t3 = t12-1.0;
t14 = b.*x1tau1_d;
t15 = b_d.*x1tau1;
t4 = t14+t15;
t5 = t4.^2;
t17 = d.*x2tau2;
t18 = t17-1.0;
t6 = tanh(t18);
t19 = t6.^2;
t7 = t19-1.0;
t21 = d.*x2tau2_d;
t22 = d_d.*x2tau2;
t8 = t21+t22;
t9 = t8.^2;
t13 = t3.^2;
t16 = t5.^2;
t20 = t7.^2;
t23 = t9.^2;
t32 = b.*x2tau1;
t33 = t32-1.0;
t24 = tanh(t33);
t34 = t24.^2;
t25 = t34-1.0;
t36 = b.*x2tau1_d;
t37 = b_d.*x2tau1;
t26 = t36+t37;
t27 = t26.^2;
t39 = d.*x1tau2;
t40 = t39-1.0;
t28 = tanh(t40);
t41 = t28.^2;
t29 = t41-1.0;
t43 = d.*x1tau2_d;
t44 = d_d.*x1tau2;
t30 = t43+t44;
t31 = t30.^2;
t35 = t25.^2;
t38 = t27.^2;
t42 = t29.^2;
t45 = t31.^2;
t46 = b_d.^2;
t47 = d_d.^2;
out1 = a.*t2.*t13.*t16.*(-3.809756552866906e1)+a_d.*t4.*t5.*t13.*1.904878276433453e1+c.*t6.*t20.*t23.*3.809756552866906e1-c_d.*t8.*t9.*t20.*1.904878276433453e1+a.*b_d.*t5.*t13.*x1tau1_d.*5.714634829300359e1-c.*d_d.*t9.*t20.*x2tau2_d.*5.714634829300359e1-a.*t2.*t3.*t12.*t16.*1.904878276433453e1+a_d.*t3.*t4.*t5.*t12.*3.809756552866906e1+c.*t6.*t7.*t19.*t23.*1.904878276433453e1-c_d.*t7.*t8.*t9.*t19.*3.809756552866906e1-a.*t2.*t3.*t46.*x1tau1_d.^2.*5.714634829300359e1+c.*t6.*t7.*t47.*x2tau2_d.^2.*5.714634829300359e1+a.*b_d.*t3.*t5.*t12.*x1tau1_d.*1.142926965860072e2-a_d.*b_d.*t2.*t3.*t4.*x1tau1_d.*1.142926965860072e2-c.*d_d.*t7.*t9.*t19.*x2tau2_d.*1.142926965860072e2+c_d.*d_d.*t6.*t7.*t8.*x2tau2_d.*1.142926965860072e2;
if nargout > 1
    out2 = a.*t24.*t35.*t38.*(-3.809756552866906e1)+a_d.*t26.*t27.*t35.*1.904878276433453e1+c.*t28.*t42.*t45.*3.809756552866906e1-c_d.*t30.*t31.*t42.*1.904878276433453e1+a.*b_d.*t27.*t35.*x2tau1_d.*5.714634829300359e1-c.*d_d.*t31.*t42.*x1tau2_d.*5.714634829300359e1-a.*t24.*t25.*t34.*t38.*1.904878276433453e1+a_d.*t25.*t26.*t27.*t34.*3.809756552866906e1+c.*t28.*t29.*t41.*t45.*1.904878276433453e1-c_d.*t29.*t30.*t31.*t41.*3.809756552866906e1-a.*t24.*t25.*t46.*x2tau1_d.^2.*5.714634829300359e1+c.*t28.*t29.*t47.*x1tau2_d.^2.*5.714634829300359e1+a.*b_d.*t25.*t27.*t34.*x2tau1_d.*1.142926965860072e2-a_d.*b_d.*t24.*t25.*t26.*x2tau1_d.*1.142926965860072e2-c.*d_d.*t29.*t31.*t41.*x1tau2_d.*1.142926965860072e2+c_d.*d_d.*t28.*t29.*t30.*x1tau2_d.*1.142926965860072e2;
end


function [out1,out2] = sym_neuron_rhs_1_5(x1,x2,x1tau1,x2tau1,x1tau2,x2tau2,a,b,c,d,tau1,tau2,x1_d,x2_d,x1tau1_d,x2tau1_d,x1tau2_d,x2tau2_d,a_d,b_d,c_d,d_d,tau1_d,tau2_d)
%SYM_NEURON_RHS_1_5
%    [OUT1,OUT2] = SYM_NEURON_RHS_1_5(X1,X2,X1TAU1,X2TAU1,X1TAU2,X2TAU2,A,B,C,D,TAU1,TAU2,X1_D,X2_D,X1TAU1_D,X2TAU1_D,X1TAU2_D,X2TAU2_D,A_D,B_D,C_D,D_D,TAU1_D,TAU2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Feb-2019 07:59:50

t14 = b.*x1tau1;
t15 = t14-1.0;
t2 = tanh(t15);
t16 = t2.^2;
t3 = t16-1.0;
t4 = t3.^2;
t17 = b.*x1tau1_d;
t18 = b_d.*x1tau1;
t5 = t17+t18;
t6 = t5.^2;
t7 = t6.^2;
t19 = d.*x2tau2;
t20 = t19-1.0;
t8 = tanh(t20);
t21 = t8.^2;
t9 = t21-1.0;
t10 = t9.^2;
t22 = d.*x2tau2_d;
t23 = d_d.*x2tau2;
t11 = t22+t23;
t12 = t11.^2;
t13 = t12.^2;
t24 = b_d.^2;
t25 = x1tau1_d.^2;
t26 = d_d.^2;
t27 = x2tau2_d.^2;
out1 = a_d.*t2.*t4.*t7.*(-1.904878276433453e2)+c_d.*t8.*t10.*t13.*1.904878276433453e2+a_d.*b_d.*t4.*t6.*x1tau1_d.*2.857317414650179e2-c_d.*d_d.*t10.*t12.*x2tau2_d.*2.857317414650179e2+a.*t3.*t4.*t5.*t7.*3.809756552866906e1+a.*t4.*t5.*t7.*t16.*2.095366104076798e2+a.*t4.*t5.*t24.*t25.*2.857317414650179e2-a_d.*t2.*t3.*t7.*t16.*9.524391382167265e1-a_d.*t2.*t3.*t24.*t25.*2.857317414650179e2-c.*t9.*t10.*t11.*t13.*3.809756552866906e1-c.*t10.*t11.*t13.*t21.*2.095366104076798e2-c.*t10.*t11.*t26.*t27.*2.857317414650179e2+c_d.*t8.*t9.*t13.*t21.*9.524391382167265e1+c_d.*t8.*t9.*t26.*t27.*2.857317414650179e2+a.*t3.*t5.*t7.*t16.^2.*3.809756552866906e1-c.*t9.*t11.*t13.*t21.^2.*3.809756552866906e1+a.*t3.*t5.*t16.*t24.*t25.*5.714634829300359e2-c.*t9.*t11.*t21.*t26.*t27.*5.714634829300359e2+a_d.*b_d.*t3.*t6.*t16.*x1tau1_d.*5.714634829300359e2-c_d.*d_d.*t9.*t12.*t21.*x2tau2_d.*5.714634829300359e2-a.*b_d.*t2.*t4.*t5.*t6.*x1tau1_d.*7.619513105733812e2+c.*d_d.*t8.*t10.*t11.*t12.*x2tau2_d.*7.619513105733812e2-a.*b_d.*t2.*t3.*t5.*t6.*t16.*x1tau1_d.*3.809756552866906e2+c.*d_d.*t8.*t9.*t11.*t12.*t21.*x2tau2_d.*3.809756552866906e2;
if nargout > 1
    t40 = b.*x2tau1;
    t41 = t40-1.0;
    t28 = tanh(t41);
    t42 = t28.^2;
    t29 = t42-1.0;
    t30 = t29.^2;
    t43 = b.*x2tau1_d;
    t44 = b_d.*x2tau1;
    t31 = t43+t44;
    t32 = t31.^2;
    t33 = t32.^2;
    t45 = d.*x1tau2;
    t46 = t45-1.0;
    t34 = tanh(t46);
    t47 = t34.^2;
    t35 = t47-1.0;
    t36 = t35.^2;
    t48 = d.*x1tau2_d;
    t49 = d_d.*x1tau2;
    t37 = t48+t49;
    t38 = t37.^2;
    t39 = t38.^2;
    t50 = x2tau1_d.^2;
    t51 = x1tau2_d.^2;
    out2 = a_d.*t28.*t30.*t33.*(-1.904878276433453e2)+c_d.*t34.*t36.*t39.*1.904878276433453e2+a_d.*b_d.*t30.*t32.*x2tau1_d.*2.857317414650179e2-c_d.*d_d.*t36.*t38.*x1tau2_d.*2.857317414650179e2+a.*t29.*t30.*t31.*t33.*3.809756552866906e1+a.*t24.*t30.*t31.*t50.*2.857317414650179e2+a.*t30.*t31.*t33.*t42.*2.095366104076798e2-a_d.*t24.*t28.*t29.*t50.*2.857317414650179e2-a_d.*t28.*t29.*t33.*t42.*9.524391382167265e1-c.*t35.*t36.*t37.*t39.*3.809756552866906e1-c.*t26.*t36.*t37.*t51.*2.857317414650179e2-c.*t36.*t37.*t39.*t47.*2.095366104076798e2+c_d.*t26.*t34.*t35.*t51.*2.857317414650179e2+c_d.*t34.*t35.*t39.*t47.*9.524391382167265e1+a.*t29.*t31.*t33.*t42.^2.*3.809756552866906e1-c.*t35.*t37.*t39.*t47.^2.*3.809756552866906e1+a.*t24.*t29.*t31.*t42.*t50.*5.714634829300359e2-c.*t26.*t35.*t37.*t47.*t51.*5.714634829300359e2+a_d.*b_d.*t29.*t32.*t42.*x2tau1_d.*5.714634829300359e2-c_d.*d_d.*t35.*t38.*t47.*x1tau2_d.*5.714634829300359e2-a.*b_d.*t28.*t30.*t31.*t32.*x2tau1_d.*7.619513105733812e2+c.*d_d.*t34.*t36.*t37.*t38.*x1tau2_d.*7.619513105733812e2-a.*b_d.*t28.*t29.*t31.*t32.*t42.*x2tau1_d.*3.809756552866906e2+c.*d_d.*t34.*t35.*t37.*t38.*t47.*x1tau2_d.*3.809756552866906e2;
end

