function varargout=sym_bp_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_bp_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_bp_demo_rhs_1_0(x,y,xt,yt,p,q,tau,x_d,y_d,xt_d,yt_d,p_d,q_d,tau_d)
%SYM_BP_DEMO_RHS_1_0
%    [OUT1,OUT2] = SYM_BP_DEMO_RHS_1_0(X,Y,XT,YT,P,Q,TAU,X_D,Y_D,XT_D,YT_D,P_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 19:15:52

out1 = p.*x+x.^2.*y;
if nargout > 1
    t2 = y.^2;
    out2 = q-yt-t2.*y;
end


function [out1,out2] = sym_bp_demo_rhs_1_1(x,y,xt,yt,p,q,tau,x_d,y_d,xt_d,yt_d,p_d,q_d,tau_d)
%SYM_BP_DEMO_RHS_1_1
%    [OUT1,OUT2] = SYM_BP_DEMO_RHS_1_1(X,Y,XT,YT,P,Q,TAU,X_D,Y_D,XT_D,YT_D,P_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 19:15:52

out1 = p.*x_d+p_d.*x+x.^2.*y_d+x.*x_d.*y.*2.0;
if nargout > 1
    out2 = q_d-yt_d-y.^2.*y_d.*3.0;
end


function [out1,out2] = sym_bp_demo_rhs_1_2(x,y,xt,yt,p,q,tau,x_d,y_d,xt_d,yt_d,p_d,q_d,tau_d)
%SYM_BP_DEMO_RHS_1_2
%    [OUT1,OUT2] = SYM_BP_DEMO_RHS_1_2(X,Y,XT,YT,P,Q,TAU,X_D,Y_D,XT_D,YT_D,P_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 19:15:53

out1 = p_d.*x_d.*2.0+x_d.^2.*y.*2.0+x.*x_d.*y_d.*4.0;
if nargout > 1
    out2 = y.*y_d.^2.*-6.0;
end


function [out1,out2] = sym_bp_demo_rhs_1_3(x,y,xt,yt,p,q,tau,x_d,y_d,xt_d,yt_d,p_d,q_d,tau_d)
%SYM_BP_DEMO_RHS_1_3
%    [OUT1,OUT2] = SYM_BP_DEMO_RHS_1_3(X,Y,XT,YT,P,Q,TAU,X_D,Y_D,XT_D,YT_D,P_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 19:15:53

out1 = x_d.^2.*y_d.*6.0;
if nargout > 1
    t2 = y_d.^2;
    out2 = t2.*y_d.*-6.0;
end


function [out1,out2] = sym_bp_demo_rhs_1_4(x,y,xt,yt,p,q,tau,x_d,y_d,xt_d,yt_d,p_d,q_d,tau_d)
%SYM_BP_DEMO_RHS_1_4
%    [OUT1,OUT2] = SYM_BP_DEMO_RHS_1_4(X,Y,XT,YT,P,Q,TAU,X_D,Y_D,XT_D,YT_D,P_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 19:15:53

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_bp_demo_rhs_1_5(x,y,xt,yt,p,q,tau,x_d,y_d,xt_d,yt_d,p_d,q_d,tau_d)
%SYM_BP_DEMO_RHS_1_5
%    [OUT1,OUT2] = SYM_BP_DEMO_RHS_1_5(X,Y,XT,YT,P,Q,TAU,X_D,Y_D,XT_D,YT_D,P_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Oct-2018 19:15:53

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end

