function varargout=sym_vdpo_mf(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_vdpo_mf_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_vdpo_mf_rhs_1_0(x,y,xtau,ytau,mu1,mu2,tau)
%SYM_VDPO_MF_RHS_1_0
%    [OUT1,OUT2] = SYM_VDPO_MF_RHS_1_0(X,Y,XTAU,YTAU,MU1,MU2,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 11:16:50

t2 = sqrt(5.0);
t3 = sqrt(3.9e1);
t4 = acos(1.7e1./2.2e1);
t5 = t4-pi;
t6 = mu2-t2.*t3.*t5.*(2.0./3.9e1);
out1 = t6.*y;
if nargout > 1
    t7 = x.^2;
    out2 = -t6.*(x+ytau./5.0+y.*(t7.*(3.0./1.0e1)-3.0./1.0e1)-(t7.*x)./2.0+(xtau.*ytau)./5.0-xtau.*(mu1+1.0)+xtau.^2./5.0+ytau.^2./5.0);
end


function [out1,out2] = sym_vdpo_mf_rhs_1_1(x,y,xtau,ytau,mu1,mu2,tau,x_d,y_d,xtau_d,ytau_d,mu1_d,mu2_d,tau_d)
%SYM_VDPO_MF_RHS_1_1
%    [OUT1,OUT2] = SYM_VDPO_MF_RHS_1_1(X,Y,XTAU,YTAU,MU1,MU2,TAU,X_D,Y_D,XTAU_D,YTAU_D,MU1_D,MU2_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 11:16:51

t2 = sqrt(5.0);
t3 = sqrt(3.9e1);
t4 = acos(1.7e1./2.2e1);
t5 = t4-pi;
t6 = mu2-t2.*t3.*t5.*(2.0./3.9e1);
out1 = mu2_d.*y+t6.*y_d;
if nargout > 1
    t7 = x.^2;
    t8 = t7.*(3.0./1.0e1);
    t9 = t8-3.0./1.0e1;
    t10 = mu1+1.0;
    out2 = -mu2_d.*(x+ytau./5.0-(t7.*x)./2.0-t10.*xtau+t9.*y+(xtau.*ytau)./5.0+xtau.^2./5.0+ytau.^2./5.0)-t6.*(x_d+ytau_d./5.0-mu1_d.*xtau-t7.*x_d.*(3.0./2.0)-t10.*xtau_d+t9.*y_d+xtau.*xtau_d.*(2.0./5.0)+(xtau.*ytau_d)./5.0+(xtau_d.*ytau)./5.0+ytau.*ytau_d.*(2.0./5.0)+x.*x_d.*y.*(3.0./5.0));
end


function [out1,out2] = sym_vdpo_mf_rhs_1_2(x,y,xtau,ytau,mu1,mu2,tau,x_d,y_d,xtau_d,ytau_d,x_d_d,y_d_d,xtau_d_d,ytau_d_d,mu1_d,mu2_d,tau_d,mu1_d_d,mu2_d_d,tau_d_d)
%SYM_VDPO_MF_RHS_1_2
%    [OUT1,OUT2] = SYM_VDPO_MF_RHS_1_2(X,Y,XTAU,YTAU,MU1,MU2,TAU,X_D,Y_D,XTAU_D,YTAU_D,X_D_D,Y_D_D,XTAU_D_D,YTAU_D_D,MU1_D,MU2_D,TAU_D,MU1_D_D,MU2_D_D,TAU_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 11:16:51

out1 = mu2_d.*y_d_d+mu2_d_d.*y_d;
if nargout > 1
    t2 = x.^2;
    t3 = t2.*(3.0./1.0e1);
    t4 = t3-3.0./1.0e1;
    t5 = mu1+1.0;
    out2 = -(mu2+sqrt(5.0).*sqrt(3.9e1).*(pi-acos(1.7e1./2.2e1)).*(2.0./3.9e1)).*(-mu1_d.*xtau_d_d-mu1_d_d.*xtau_d+xtau_d.*xtau_d_d.*(2.0./5.0)+(xtau_d.*ytau_d_d)./5.0+(xtau_d_d.*ytau_d)./5.0+ytau_d.*ytau_d_d.*(2.0./5.0)-x.*x_d.*x_d_d.*3.0+x.*x_d.*y_d_d.*(3.0./5.0)+x.*x_d_d.*y_d.*(3.0./5.0)+x_d.*x_d_d.*y.*(3.0./5.0))-mu2_d_d.*(x_d+ytau_d./5.0-mu1_d.*xtau-t2.*x_d.*(3.0./2.0)-t5.*xtau_d+t4.*y_d+xtau.*xtau_d.*(2.0./5.0)+(xtau.*ytau_d)./5.0+(xtau_d.*ytau)./5.0+ytau.*ytau_d.*(2.0./5.0)+x.*x_d.*y.*(3.0./5.0))-mu2_d.*(x_d_d+ytau_d_d./5.0-mu1_d_d.*xtau-t2.*x_d_d.*(3.0./2.0)-t5.*xtau_d_d+t4.*y_d_d+xtau.*xtau_d_d.*(2.0./5.0)+(xtau.*ytau_d_d)./5.0+(xtau_d_d.*ytau)./5.0+ytau.*ytau_d_d.*(2.0./5.0)+x.*x_d_d.*y.*(3.0./5.0));
end


function [out1,out2] = sym_vdpo_mf_rhs_1_3(x,y,xtau,ytau,mu1,mu2,tau,x_d,y_d,xtau_d,ytau_d,x_d_d,y_d_d,xtau_d_d,ytau_d_d,x_d_d_d,y_d_d_d,xtau_d_d_d,ytau_d_d_d,mu1_d,mu2_d,tau_d,mu1_d_d,mu2_d_d,tau_d_d,mu1_d_d_d,mu2_d_d_d,tau_d_d_d)
%SYM_VDPO_MF_RHS_1_3
%    [OUT1,OUT2] = SYM_VDPO_MF_RHS_1_3(X,Y,XTAU,YTAU,MU1,MU2,TAU,X_D,Y_D,XTAU_D,YTAU_D,X_D_D,Y_D_D,XTAU_D_D,YTAU_D_D,X_D_D_D,Y_D_D_D,XTAU_D_D_D,YTAU_D_D_D,MU1_D,MU2_D,TAU_D,MU1_D_D,MU2_D_D,TAU_D_D,MU1_D_D_D,MU2_D_D_D,TAU_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 11:16:51

out1 = 0.0;
if nargout > 1
    out2 = -mu2_d_d_d.*(-mu1_d.*xtau_d_d-mu1_d_d.*xtau_d+xtau_d.*xtau_d_d.*(2.0./5.0)+(xtau_d.*ytau_d_d)./5.0+(xtau_d_d.*ytau_d)./5.0+ytau_d.*ytau_d_d.*(2.0./5.0)-x.*x_d.*x_d_d.*3.0+x.*x_d.*y_d_d.*(3.0./5.0)+x.*x_d_d.*y_d.*(3.0./5.0)+x_d.*x_d_d.*y.*(3.0./5.0))-mu2_d_d.*(-mu1_d.*xtau_d_d_d-mu1_d_d_d.*xtau_d+xtau_d.*xtau_d_d_d.*(2.0./5.0)+(xtau_d.*ytau_d_d_d)./5.0+(xtau_d_d_d.*ytau_d)./5.0+ytau_d.*ytau_d_d_d.*(2.0./5.0)-x.*x_d.*x_d_d_d.*3.0+x.*x_d.*y_d_d_d.*(3.0./5.0)+x.*x_d_d_d.*y_d.*(3.0./5.0)+x_d.*x_d_d_d.*y.*(3.0./5.0))-mu2_d.*(-mu1_d_d.*xtau_d_d_d-mu1_d_d_d.*xtau_d_d+xtau_d_d.*xtau_d_d_d.*(2.0./5.0)+(xtau_d_d.*ytau_d_d_d)./5.0+(xtau_d_d_d.*ytau_d_d)./5.0+ytau_d_d.*ytau_d_d_d.*(2.0./5.0)-x.*x_d_d.*x_d_d_d.*3.0+x.*x_d_d.*y_d_d_d.*(3.0./5.0)+x.*x_d_d_d.*y_d_d.*(3.0./5.0)+x_d_d.*x_d_d_d.*y.*(3.0./5.0))-(mu2+sqrt(5.0).*sqrt(3.9e1).*(pi-acos(1.7e1./2.2e1)).*(2.0./3.9e1)).*(x_d.*x_d_d.*x_d_d_d.*-3.0+x_d.*x_d_d.*y_d_d_d.*(3.0./5.0)+x_d.*x_d_d_d.*y_d_d.*(3.0./5.0)+x_d_d.*x_d_d_d.*y_d.*(3.0./5.0));
end


function [out1,out2] = sym_vdpo_mf_rhs_1_4(x,y,xtau,ytau,mu1,mu2,tau,x_d,y_d,xtau_d,ytau_d,x_d_d,y_d_d,xtau_d_d,ytau_d_d,x_d_d_d,y_d_d_d,xtau_d_d_d,ytau_d_d_d,x_d_d_d_d,y_d_d_d_d,xtau_d_d_d_d,ytau_d_d_d_d,mu1_d,mu2_d,tau_d,mu1_d_d,mu2_d_d,tau_d_d,mu1_d_d_d,mu2_d_d_d,tau_d_d_d,mu1_d_d_d_d,mu2_d_d_d_d,tau_d_d_d_d)
%SYM_VDPO_MF_RHS_1_4
%    [OUT1,OUT2] = SYM_VDPO_MF_RHS_1_4(X,Y,XTAU,YTAU,MU1,MU2,TAU,X_D,Y_D,XTAU_D,YTAU_D,X_D_D,Y_D_D,XTAU_D_D,YTAU_D_D,X_D_D_D,Y_D_D_D,XTAU_D_D_D,YTAU_D_D_D,X_D_D_D_D,Y_D_D_D_D,XTAU_D_D_D_D,YTAU_D_D_D_D,MU1_D,MU2_D,TAU_D,MU1_D_D,MU2_D_D,TAU_D_D,MU1_D_D_D,MU2_D_D_D,TAU_D_D_D,MU1_D_D_D_D,MU2_D_D_D_D,TAU_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 11:16:52

out1 = 0.0;
if nargout > 1
    out2 = -mu2_d_d_d_d.*(x_d.*x_d_d.*x_d_d_d.*-3.0+x_d.*x_d_d.*y_d_d_d.*(3.0./5.0)+x_d.*x_d_d_d.*y_d_d.*(3.0./5.0)+x_d_d.*x_d_d_d.*y_d.*(3.0./5.0))-mu2_d_d_d.*(x_d.*x_d_d.*x_d_d_d_d.*-3.0+x_d.*x_d_d.*y_d_d_d_d.*(3.0./5.0)+x_d.*x_d_d_d_d.*y_d_d.*(3.0./5.0)+x_d_d.*x_d_d_d_d.*y_d.*(3.0./5.0))-mu2_d_d.*(x_d.*x_d_d_d.*x_d_d_d_d.*-3.0+x_d.*x_d_d_d.*y_d_d_d_d.*(3.0./5.0)+x_d.*x_d_d_d_d.*y_d_d_d.*(3.0./5.0)+x_d_d_d.*x_d_d_d_d.*y_d.*(3.0./5.0))-mu2_d.*(x_d_d.*x_d_d_d.*x_d_d_d_d.*-3.0+x_d_d.*x_d_d_d.*y_d_d_d_d.*(3.0./5.0)+x_d_d.*x_d_d_d_d.*y_d_d_d.*(3.0./5.0)+x_d_d_d.*x_d_d_d_d.*y_d_d.*(3.0./5.0));
end


function [out1,out2] = sym_vdpo_mf_rhs_1_5(x,y,xtau,ytau,mu1,mu2,tau,x_d,y_d,xtau_d,ytau_d,x_d_d,y_d_d,xtau_d_d,ytau_d_d,x_d_d_d,y_d_d_d,xtau_d_d_d,ytau_d_d_d,x_d_d_d_d,y_d_d_d_d,xtau_d_d_d_d,ytau_d_d_d_d,x_d_d_d_d_d,y_d_d_d_d_d,xtau_d_d_d_d_d,ytau_d_d_d_d_d,mu1_d,mu2_d,tau_d,mu1_d_d,mu2_d_d,tau_d_d,mu1_d_d_d,mu2_d_d_d,tau_d_d_d,mu1_d_d_d_d,mu2_d_d_d_d,tau_d_d_d_d,mu1_d_d_d_d_d,mu2_d_d_d_d_d,tau_d_d_d_d_d)
%SYM_VDPO_MF_RHS_1_5
%    [OUT1,OUT2] = SYM_VDPO_MF_RHS_1_5(X,Y,XTAU,YTAU,MU1,MU2,TAU,X_D,Y_D,XTAU_D,YTAU_D,X_D_D,Y_D_D,XTAU_D_D,YTAU_D_D,X_D_D_D,Y_D_D_D,XTAU_D_D_D,YTAU_D_D_D,X_D_D_D_D,Y_D_D_D_D,XTAU_D_D_D_D,YTAU_D_D_D_D,X_D_D_D_D_D,Y_D_D_D_D_D,XTAU_D_D_D_D_D,YTAU_D_D_D_D_D,MU1_D,MU2_D,TAU_D,MU1_D_D,MU2_D_D,TAU_D_D,MU1_D_D_D,MU2_D_D_D,TAU_D_D_D,MU1_D_D_D_D,MU2_D_D_D_D,TAU_D_D_D_D,MU1_D_D_D_D_D,MU2_D_D_D_D_D,TAU_D_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 11:16:52

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end

