function varargout=sym_acs(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_acs_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_acs_rhs_1_0(x,y,xtau,ytau,zeta,tau,tau_scaled,x_d,y_d,xtau_d,ytau_d,zeta_d,tau_d,tau_scaled_d)
%SYM_ACS_RHS_1_0
%    [OUT1,OUT2] = SYM_ACS_RHS_1_0(X,Y,XTAU,YTAU,ZETA,TAU,TAU_SCALED,X_D,Y_D,XTAU_D,YTAU_D,ZETA_D,TAU_D,TAU_SCALED_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 13:36:30

out1 = tau.*y;
if nargout > 1
    t2 = xtau.^2;
    out2 = -tau.*(x+xtau./1.0e1+ytau.*(1.3e1./2.5e1)-(t2.*xtau)./1.0e1+y.*zeta.*2.0);
end


function [out1,out2] = sym_acs_rhs_1_1(x,y,xtau,ytau,zeta,tau,tau_scaled,x_d,y_d,xtau_d,ytau_d,zeta_d,tau_d,tau_scaled_d)
%SYM_ACS_RHS_1_1
%    [OUT1,OUT2] = SYM_ACS_RHS_1_1(X,Y,XTAU,YTAU,ZETA,TAU,TAU_SCALED,X_D,Y_D,XTAU_D,YTAU_D,ZETA_D,TAU_D,TAU_SCALED_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 13:36:30

out1 = tau_d.*y+tau.*y_d;
if nargout > 1
    t2 = xtau.^2;
    out2 = -tau.*(x_d+xtau_d./1.0e1+ytau_d.*(1.3e1./2.5e1)-t2.*xtau_d.*(3.0./1.0e1)+y.*zeta_d.*2.0+y_d.*zeta.*2.0)-tau_d.*(x+xtau./1.0e1+ytau.*(1.3e1./2.5e1)-(t2.*xtau)./1.0e1+y.*zeta.*2.0);
end


function [out1,out2] = sym_acs_rhs_1_2(x,y,xtau,ytau,zeta,tau,tau_scaled,x_d,y_d,xtau_d,ytau_d,zeta_d,tau_d,tau_scaled_d)
%SYM_ACS_RHS_1_2
%    [OUT1,OUT2] = SYM_ACS_RHS_1_2(X,Y,XTAU,YTAU,ZETA,TAU,TAU_SCALED,X_D,Y_D,XTAU_D,YTAU_D,ZETA_D,TAU_D,TAU_SCALED_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 13:36:30

out1 = tau_d.*y_d.*2.0;
if nargout > 1
    out2 = -tau.*(y_d.*zeta_d.*4.0-xtau.*xtau_d.^2.*(3.0./5.0))-tau_d.*(x_d+xtau_d./1.0e1+ytau_d.*(1.3e1./2.5e1)+y.*zeta_d.*2.0+y_d.*zeta.*2.0-xtau.^2.*xtau_d.*(3.0./1.0e1)).*2.0;
end


function [out1,out2] = sym_acs_rhs_1_3(x,y,xtau,ytau,zeta,tau,tau_scaled,x_d,y_d,xtau_d,ytau_d,zeta_d,tau_d,tau_scaled_d)
%SYM_ACS_RHS_1_3
%    [OUT1,OUT2] = SYM_ACS_RHS_1_3(X,Y,XTAU,YTAU,ZETA,TAU,TAU_SCALED,X_D,Y_D,XTAU_D,YTAU_D,ZETA_D,TAU_D,TAU_SCALED_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 13:36:30

out1 = 0.0;
if nargout > 1
    t2 = xtau_d.^2;
    out2 = tau_d.*(t2.*xtau.*(3.0./5.0)-y_d.*zeta_d.*4.0).*3.0+t2.*tau.*xtau_d.*(3.0./5.0);
end


function [out1,out2] = sym_acs_rhs_1_4(x,y,xtau,ytau,zeta,tau,tau_scaled,x_d,y_d,xtau_d,ytau_d,zeta_d,tau_d,tau_scaled_d)
%SYM_ACS_RHS_1_4
%    [OUT1,OUT2] = SYM_ACS_RHS_1_4(X,Y,XTAU,YTAU,ZETA,TAU,TAU_SCALED,X_D,Y_D,XTAU_D,YTAU_D,ZETA_D,TAU_D,TAU_SCALED_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 13:36:30

out1 = 0.0;
if nargout > 1
    t2 = xtau_d.^2;
    out2 = t2.*tau_d.*xtau_d.*(1.2e1./5.0);
end


function [out1,out2] = sym_acs_rhs_1_5(x,y,xtau,ytau,zeta,tau,tau_scaled,x_d,y_d,xtau_d,ytau_d,zeta_d,tau_d,tau_scaled_d)
%SYM_ACS_RHS_1_5
%    [OUT1,OUT2] = SYM_ACS_RHS_1_5(X,Y,XTAU,YTAU,ZETA,TAU,TAU_SCALED,X_D,Y_D,XTAU_D,YTAU_D,ZETA_D,TAU_D,TAU_SCALED_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Sep-2018 13:36:31

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end

