%% DDE-Biftool code
clear
ntau=2;
funcs=set_funcs(...
    'sys_rhs',@(x,p)p-x(1,ntau+1,:),...
    'sys_ntau',@()ntau,...
    'sys_tau',@(nr,x,p)x(1,nr,:),'x_vectorized',true);
eqbr=SetupStst(funcs,'contpar',1,'x',pi/2,...
    'parameter',pi/2-1e-2,'step',0.1);
hopf=SetupHopf(funcs,eqbr,1);
hpl1=nmfm_func_hopf(funcs,hopf.point,'output',1);
display(hpl1.nmfm.L1,'L1');
