function varargout=sym_RH(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_RH_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2,out3] = sym_RH_rhs_1_0(x,y,z,xt,yt,zt,Iapp,S,tau,a,b,c,d,chi,r)
%SYM_RH_RHS_1_0
%    [OUT1,OUT2,OUT3] = SYM_RH_RHS_1_0(X,Y,Z,XT,YT,ZT,IAPP,S,TAU,A,B,C,D,CHI,R)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2018 01:38:57

t2 = x.^2;
out1 = Iapp+y-c.*z+b.*xt.^2-a.*t2.*x;
if nargout > 1
    out2 = c-y-d.*t2;
end
if nargout > 2
    out3 = -r.*(z+S.*(chi-x));
end


function [out1,out2,out3] = sym_RH_rhs_1_1(x,y,z,xt,yt,zt,Iapp,S,tau,a,b,c,d,chi,r,x_d,y_d,z_d,xt_d,yt_d,zt_d,Iapp_d,S_d,tau_d,a_d,b_d,c_d,d_d,chi_d,r_d)
%SYM_RH_RHS_1_1
%    [OUT1,OUT2,OUT3] = SYM_RH_RHS_1_1(X,Y,Z,XT,YT,ZT,IAPP,S,TAU,A,B,C,D,CHI,R,X_D,Y_D,Z_D,XT_D,YT_D,ZT_D,IAPP_D,S_D,TAU_D,A_D,B_D,C_D,D_D,CHI_D,R_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2018 01:38:57

t2 = x.^2;
out1 = Iapp_d+y_d-c.*z_d-c_d.*z+b_d.*xt.^2-a.*t2.*x_d.*3.0-a_d.*t2.*x+b.*xt.*xt_d.*2.0;
if nargout > 1
    out2 = c_d-y_d-d_d.*t2-d.*x.*x_d.*2.0;
end
if nargout > 2
    t3 = chi-x;
    out3 = -r.*(z_d+S_d.*t3+S.*(chi_d-x_d))-r_d.*(z+S.*t3);
end


function [out1,out2,out3] = sym_RH_rhs_1_2(x,y,z,xt,yt,zt,Iapp,S,tau,a,b,c,d,chi,r,x_d,y_d,z_d,xt_d,yt_d,zt_d,x_d_d,y_d_d,z_d_d,xt_d_d,yt_d_d,zt_d_d,Iapp_d,S_d,tau_d,a_d,b_d,c_d,d_d,chi_d,r_d,Iapp_d_d,S_d_d,tau_d_d,a_d_d,b_d_d,c_d_d,d_d_d,chi_d_d,r_d_d)
%SYM_RH_RHS_1_2
%    [OUT1,OUT2,OUT3] = SYM_RH_RHS_1_2(X,Y,Z,XT,YT,ZT,IAPP,S,TAU,A,B,C,D,CHI,R,X_D,Y_D,Z_D,XT_D,YT_D,ZT_D,X_D_D,Y_D_D,Z_D_D,XT_D_D,YT_D_D,ZT_D_D,IAPP_D,S_D,TAU_D,A_D,B_D,C_D,D_D,CHI_D,R_D,IAPP_D_D,S_D_D,TAU_D_D,A_D_D,B_D_D,C_D_D,D_D_D,CHI_D_D,R_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2018 01:38:57

t2 = x.^2;
out1 = -c_d.*z_d_d-c_d_d.*z_d-a_d.*t2.*x_d_d.*3.0-a_d_d.*t2.*x_d.*3.0+b.*xt_d.*xt_d_d.*2.0+b_d.*xt.*xt_d_d.*2.0+b_d_d.*xt.*xt_d.*2.0-a.*x.*x_d.*x_d_d.*6.0;
if nargout > 1
    out2 = d.*x_d.*x_d_d.*-2.0-d_d.*x.*x_d_d.*2.0-d_d_d.*x.*x_d.*2.0;
end
if nargout > 2
    t3 = chi-x;
    t4 = chi_d-x_d;
    t5 = chi_d_d-x_d_d;
    out3 = -r.*(S_d.*t5+S_d_d.*t4)-r_d_d.*(z_d+S.*t4+S_d.*t3)-r_d.*(z_d_d+S.*t5+S_d_d.*t3);
end


function [out1,out2,out3] = sym_RH_rhs_1_3(x,y,z,xt,yt,zt,Iapp,S,tau,a,b,c,d,chi,r,x_d,y_d,z_d,xt_d,yt_d,zt_d,x_d_d,y_d_d,z_d_d,xt_d_d,yt_d_d,zt_d_d,x_d_d_d,y_d_d_d,z_d_d_d,xt_d_d_d,yt_d_d_d,zt_d_d_d,Iapp_d,S_d,tau_d,a_d,b_d,c_d,d_d,chi_d,r_d,Iapp_d_d,S_d_d,tau_d_d,a_d_d,b_d_d,c_d_d,d_d_d,chi_d_d,r_d_d,Iapp_d_d_d,S_d_d_d,tau_d_d_d,a_d_d_d,b_d_d_d,c_d_d_d,d_d_d_d,chi_d_d_d,r_d_d_d)
%SYM_RH_RHS_1_3
%    [OUT1,OUT2,OUT3] = SYM_RH_RHS_1_3(X,Y,Z,XT,YT,ZT,IAPP,S,TAU,A,B,C,D,CHI,R,X_D,Y_D,Z_D,XT_D,YT_D,ZT_D,X_D_D,Y_D_D,Z_D_D,XT_D_D,YT_D_D,ZT_D_D,X_D_D_D,Y_D_D_D,Z_D_D_D,XT_D_D_D,YT_D_D_D,ZT_D_D_D,IAPP_D,S_D,TAU_D,A_D,B_D,C_D,D_D,CHI_D,R_D,IAPP_D_D,S_D_D,TAU_D_D,A_D_D,B_D_D,C_D_D,D_D_D,CHI_D_D,R_D_D,IAPP_D_D_D,S_D_D_D,TAU_D_D_D,A_D_D_D,B_D_D_D,C_D_D_D,D_D_D_D,CHI_D_D_D,R_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2018 01:38:57

out1 = b_d.*xt_d_d.*xt_d_d_d.*2.0+b_d_d.*xt_d.*xt_d_d_d.*2.0+b_d_d_d.*xt_d.*xt_d_d.*2.0-a.*x_d.*x_d_d.*x_d_d_d.*6.0-a_d.*x.*x_d_d.*x_d_d_d.*6.0-a_d_d.*x.*x_d.*x_d_d_d.*6.0-a_d_d_d.*x.*x_d.*x_d_d.*6.0;
if nargout > 1
    out2 = d_d.*x_d_d.*x_d_d_d.*-2.0-d_d_d.*x_d.*x_d_d_d.*2.0-d_d_d_d.*x_d.*x_d_d.*2.0;
end
if nargout > 2
    t2 = chi_d-x_d;
    t3 = chi_d_d-x_d_d;
    t4 = chi_d_d_d-x_d_d_d;
    out3 = -r_d_d_d.*(S_d.*t3+S_d_d.*t2)-r_d_d.*(S_d.*t4+S_d_d_d.*t2)-r_d.*(S_d_d.*t4+S_d_d_d.*t3);
end


function [out1,out2,out3] = sym_RH_rhs_1_4(x,y,z,xt,yt,zt,Iapp,S,tau,a,b,c,d,chi,r,x_d,y_d,z_d,xt_d,yt_d,zt_d,x_d_d,y_d_d,z_d_d,xt_d_d,yt_d_d,zt_d_d,x_d_d_d,y_d_d_d,z_d_d_d,xt_d_d_d,yt_d_d_d,zt_d_d_d,x_d_d_d_d,y_d_d_d_d,z_d_d_d_d,xt_d_d_d_d,yt_d_d_d_d,zt_d_d_d_d,Iapp_d,S_d,tau_d,a_d,b_d,c_d,d_d,chi_d,r_d,Iapp_d_d,S_d_d,tau_d_d,a_d_d,b_d_d,c_d_d,d_d_d,chi_d_d,r_d_d,Iapp_d_d_d,S_d_d_d,tau_d_d_d,a_d_d_d,b_d_d_d,c_d_d_d,d_d_d_d,chi_d_d_d,r_d_d_d,Iapp_d_d_d_d,S_d_d_d_d,tau_d_d_d_d,a_d_d_d_d,b_d_d_d_d,c_d_d_d_d,d_d_d_d_d,chi_d_d_d_d,r_d_d_d_d)
%SYM_RH_RHS_1_4
%    [OUT1,OUT2,OUT3] = SYM_RH_RHS_1_4(X,Y,Z,XT,YT,ZT,IAPP,S,TAU,A,B,C,D,CHI,R,X_D,Y_D,Z_D,XT_D,YT_D,ZT_D,X_D_D,Y_D_D,Z_D_D,XT_D_D,YT_D_D,ZT_D_D,X_D_D_D,Y_D_D_D,Z_D_D_D,XT_D_D_D,YT_D_D_D,ZT_D_D_D,X_D_D_D_D,Y_D_D_D_D,Z_D_D_D_D,XT_D_D_D_D,YT_D_D_D_D,ZT_D_D_D_D,IAPP_D,S_D,TAU_D,A_D,B_D,C_D,D_D,CHI_D,R_D,IAPP_D_D,S_D_D,TAU_D_D,A_D_D,B_D_D,C_D_D,D_D_D,CHI_D_D,R_D_D,IAPP_D_D_D,S_D_D_D,TAU_D_D_D,A_D_D_D,B_D_D_D,C_D_D_D,D_D_D_D,CHI_D_D_D,R_D_D_D,IAPP_D_D_D_D,S_D_D_D_D,TAU_D_D_D_D,A_D_D_D_D,B_D_D_D_D,C_D_D_D_D,D_D_D_D_D,CHI_D_D_D_D,R_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2018 01:38:58

out1 = a_d.*x_d_d.*x_d_d_d.*x_d_d_d_d.*-6.0-a_d_d.*x_d.*x_d_d_d.*x_d_d_d_d.*6.0-a_d_d_d.*x_d.*x_d_d.*x_d_d_d_d.*6.0-a_d_d_d_d.*x_d.*x_d_d.*x_d_d_d.*6.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end


function [out1,out2,out3] = sym_RH_rhs_1_5(x,y,z,xt,yt,zt,Iapp,S,tau,a,b,c,d,chi,r,x_d,y_d,z_d,xt_d,yt_d,zt_d,x_d_d,y_d_d,z_d_d,xt_d_d,yt_d_d,zt_d_d,x_d_d_d,y_d_d_d,z_d_d_d,xt_d_d_d,yt_d_d_d,zt_d_d_d,x_d_d_d_d,y_d_d_d_d,z_d_d_d_d,xt_d_d_d_d,yt_d_d_d_d,zt_d_d_d_d,x_d_d_d_d_d,y_d_d_d_d_d,z_d_d_d_d_d,xt_d_d_d_d_d,yt_d_d_d_d_d,zt_d_d_d_d_d,Iapp_d,S_d,tau_d,a_d,b_d,c_d,d_d,chi_d,r_d,Iapp_d_d,S_d_d,tau_d_d,a_d_d,b_d_d,c_d_d,d_d_d,chi_d_d,r_d_d,Iapp_d_d_d,S_d_d_d,tau_d_d_d,a_d_d_d,b_d_d_d,c_d_d_d,d_d_d_d,chi_d_d_d,r_d_d_d,Iapp_d_d_d_d,S_d_d_d_d,tau_d_d_d_d,a_d_d_d_d,b_d_d_d_d,c_d_d_d_d,d_d_d_d_d,chi_d_d_d_d,r_d_d_d_d,Iapp_d_d_d_d_d,S_d_d_d_d_d,tau_d_d_d_d_d,a_d_d_d_d_d,b_d_d_d_d_d,c_d_d_d_d_d,d_d_d_d_d_d,chi_d_d_d_d_d,r_d_d_d_d_d)
%SYM_RH_RHS_1_5
%    [OUT1,OUT2,OUT3] = SYM_RH_RHS_1_5(X,Y,Z,XT,YT,ZT,IAPP,S,TAU,A,B,C,D,CHI,R,X_D,Y_D,Z_D,XT_D,YT_D,ZT_D,X_D_D,Y_D_D,Z_D_D,XT_D_D,YT_D_D,ZT_D_D,X_D_D_D,Y_D_D_D,Z_D_D_D,XT_D_D_D,YT_D_D_D,ZT_D_D_D,X_D_D_D_D,Y_D_D_D_D,Z_D_D_D_D,XT_D_D_D_D,YT_D_D_D_D,ZT_D_D_D_D,X_D_D_D_D_D,Y_D_D_D_D_D,Z_D_D_D_D_D,XT_D_D_D_D_D,YT_D_D_D_D_D,ZT_D_D_D_D_D,IAPP_D,S_D,TAU_D,A_D,B_D,C_D,D_D,CHI_D,R_D,IAPP_D_D,S_D_D,TAU_D_D,A_D_D,B_D_D,C_D_D,D_D_D,CHI_D_D,R_D_D,IAPP_D_D_D,S_D_D_D,TAU_D_D_D,A_D_D_D,B_D_D_D,C_D_D_D,D_D_D_D,CHI_D_D_D,R_D_D_D,IAPP_D_D_D_D,S_D_D_D_D,TAU_D_D_D_D,A_D_D_D_D,B_D_D_D_D,C_D_D_D_D,D_D_D_D_D,CHI_D_D_D_D,R_D_D_D_D,IAPP_D_D_D_D_D,S_D_D_D_D_D,TAU_D_D_D_D_D,A_D_D_D_D_D,B_D_D_D_D_D,C_D_D_D_D_D,D_D_D_D_D_D,CHI_D_D_D_D_D,R_D_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Oct-2018 01:38:58

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end

